### ISSUE TITLE
Will there be support to document commands?

### ISSUE THREAD

**Issue by sofiaguyang** [asyncapi/asyncapi#11]
The specs seem to focus on events emitted. Will there be support to document commands, too?

**Comment by fmvilas** [comment]
The spec is focused on messages. The meaning of those messages can be anything, from an event to a command/action/request or whatever you want to put there. I would say that examples are focused on events but not the spec. You might want to have a look at https://github.com/asyncapi/topic-definition where we consider the option of sending actions as messages.

**Comment by fmvilas** [comment]
I'm closing this but if you think my answer doesn't address the question please don't hesitate to tell us. Thanks for your question!
