### ISSUE TITLE
[FEATURE REQUEST] Add a way to differentiate headers from application headers

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#112]
**Is your feature request related to a problem? Please describe.**
When mapping message header definitions to protocols such as JMS or AMQP 1.0, it's important to differentiate headers from application headers. AMQP defines them as properties and applicationProperties respectively. JMS defines them as headers and properties respectively.

Therefore, we should have a way to label a header as an `applicationHeader`.

**Can't it be tackled using specification extensions?**
Yes, but this way we standardize the behavior.

**Describe the solution you'd like**
Don't have a solution yet. Will make a proposal soon.

**Describe alternatives you've considered**
Making it a specification extension.

**Comment by fmvilas** [comment]
Probably the best option is to remove headers from the spec and leave it for the protocol mappers. In any case, the protocol mappers must support this feature.

**Comment by SensibleWood** [comment]
Working on this issue

**Comment by SensibleWood** [comment]
Merged #169 into master so closing this guy down (not sure why it didn't auto close, anyhoo...)
