### ISSUE TITLE
Why not asyncapi.org

### ISSUE THREAD

**Issue by andresgutgon** [asyncapi/asyncapi#12]
Hi, it's not technical question. But I think is related with this repo.

Why if it's an Open protocol project page is on a `.com` domain and on `.org`. I see other projects using it. Ex.:
1. http://ogp.me/ (Open Graph Protocol) 
2. http://www.wordpress.org

Thanks and sorry if it's a dump question

You're doing a great work :clap:

**Comment by fmvilas** [comment]
Hey Andrés! That's not a dumb question at all. We also registered asyncapi.org for the same reason you explain. Why we chose `.com`? To be fair we didn't even thought about it. It was natural for us to think about the `.com` as the default one because it's what more people are used to 😊 

Thanks!

**Comment by andresgutgon** [comment]
Thanks @fmvilas :)

**Comment by andresgutgon** [comment]
I noticed https://www.asyncapi.org is not redirecting to `.com`. it works without `www`

**Comment by fmvilas** [comment]
Oh! great catch @andresgutgon. We'll fix it. Thanks!

**Comment by fmvilas** [comment]
It's working now. Thanks for reporting @andresgutgon.

**Comment by andresgutgon** [comment]
💪

**Comment by fmvilas** [comment]
I'm closing the issue now but don't hesitate to continue discussion or open a new issue if you see something else :)

**Comment by andresgutgon** [comment]
Well original question is why you don't promote `.org` domain. For me feels more Open than a `.com` :)

**Comment by fmvilas** [comment]
I already started promoting the `.org` in some tweets. I think for now we'll do both.

**Comment by bpedro** [comment]
Adding my thoughts here: usually `.org` TLD subdomains are associated with **non-commercial** organizations. We ended up choosing the `.com` TLD for the sake of transparency—we are a commercial company.

Thanks for sharing your thoughts and helping us improve!

**Comment by andresgutgon** [comment]
I know. But Facebook started http://ogp.me/ Open Graph Protocol. The protocol is Open but Facebook doesn't.

Imo the company and the protocol can be different things. 

I could implement `asyncapi` without been a `Hitch` customer, right?

Btw I love you're thinking about transparency 👏

**Comment by bpedro** [comment]
@andresgutgon Thanks!

Yes, you're totally correct, anyone can use the Async API specification without being a Hitch customer.

In any case, both domains work and we'll be promoting https://www.asyncapi.org more.
