### ISSUE TITLE
Create a team/contributors document

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#122]
As a contributor, I'd like to get recognition for my contributions and appear as a project contributor/maintainer.

**Comment by derberg** [comment]
do you have something specific in mind
I bumped into this interesting solution https://all-contributors.js.org/ 
example: https://github.com/jaredpalmer/formik#contributors

**Comment by fmvilas** [comment]
That looks great! Would you like to pick this issue?

**Comment by derberg** [comment]
definitely 💃

**Comment by derberg** [comment]
So far I integrated all-contributors only with asyncapi-react as I have rights only there.

- you can talk to bot any time in any context, issue or PR. Example issue: https://github.com/asyncapi/asyncapi-react/issues/36
- bot replies he hears you and creates a pull request with change in readme file to add new contributor. Example https://github.com/asyncapi/asyncapi-react/pull/37 
- not only code contrib is valuable, this is why it supports different emojis https://github.com/all-contributors/all-contributors#emoji-key
- readme gets a badge about contributors and a section with nice overview of contributors

**Comment by derberg** [comment]
summary:

- advantage
  - automation with bot, flexibility
  - nice outcome
  - emojis do not have to be used
- disadvantage 
  - bot creates branches in main repo, so if you have strict rule that all work comes in through forks, this might be a problem for ya
  - bot shows as one of contributors https://github.com/asyncapi/asyncapi-react/graphs/contributors, but maybe this is also advantage as he is the only one making those additions and by this approach it is more clean, the contributors section is clear thanks to it

**Comment by derberg** [comment]
@fmvilas let me know whay you think, remember I'm out next week so if I need to join SIG meeting to talk about that, I'll do that but week after

**Comment by fmvilas** [comment]
I just made available the @all-contributors app to all the repos in the organization.

**Comment by fmvilas** [comment]
LOL. Ok let's use it!

**Comment by fmvilas** [comment]
@all-contributors please add @derberg for doc, ideas and review

**Comment by fmvilas** [comment]
@all-contributors please add @MikeRalphson for question, doc, code, ideas, infra, review and test.

**Comment by fmvilas** [comment]
@all-contributors please add @rmelian for question, bug, code, doc, ideas, maintenance, review, tool and test.

**Comment by fmvilas** [comment]
@all-contributors please add @MikeRalphson for question, doc, code, ideas, infra, review and test.

**Comment by fmvilas** [comment]
@all-contributors please add @rmelian for question, bug, code, doc, ideas, maintenance, review, tool and test.

**Comment by fmvilas** [comment]
@all-contributors please add @fmvilas for question, bug, blog, business, code, content, doc, design, examples, financial, fundingFinding, ideas, infra, maintenance, plugin, review, tool, test, tutorial, and talk.

**Comment by fmvilas** [comment]
@all-contributors please add @MikeRalphson for maintenance and tool.

**Comment by fmvilas** [comment]
LOL @derberg, your picture became really small 😄

**Comment by fmvilas** [comment]
@all-contributors please add @dulcedelarosa for design

**Comment by fmvilas** [comment]
For those who don't know, @dulcedelarosa is the logo designer!

**Comment by derberg** [comment]
@fmvilas dude, your fault, you're too active! they did not predict this level of contribution and did not prepare to scale that much

**Comment by fmvilas** [comment]
@all-contributors please add @SensibleWood for code, documentation and ideas.

**Comment by fmvilas** [comment]
I'm closing the issue. Thanks for the recommendation @derberg!

**Comment by fmvilas** [comment]
@all-contributors

**Comment by fmvilas** [comment]
@all-contributors update

**Comment by fmvilas** [comment]
@all-contributors setup
