### ISSUE TITLE
Launch AsyncAPI 2.0.0

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#154]
This issue serves as an "Epic" for the launch of AsyncAPI 2.0.0.

**Comment by vit1251** [comment]
Could you please provide websocket examples. Totally misunderstand how to describe single channel like /ws with few subscribe/publish messages.

**Comment by fmvilas** [comment]
Hi @vit1251. Can you please create an issue for that? This issue is completely unrelated and your question will be forgotten. Thanks!

PS: I'll soon create guides on how to use AsyncAPI with different protocols and in different scenarios.

**Comment by vit1251** [comment]
@fmvilas I create #253 as you suggest.

**Comment by vit1251** [comment]
@fmvilas hello, now I receive 2.0.0 pre-release update and you 20 day ago make a promise to provide WebSocket using gudie example. Any changes? It very important because most users use WebSocket as event bus and exchange message right now.

**Comment by fmvilas** [comment]
Hey, @vit1251. I'll provide a good example using WebSockets soon. Sorry, I'm doing too many things. Don't worry, the spec is being tested in real scenarios and some of them include WebSockets. I just can't share them as they are internal APIs of the companies I work with. Again, I'll find time after the release to showcase different use cases and protocols.
