### ISSUE TITLE
Unlink topic description from payloads

### ISSUE THREAD

**Issue by ignasi35** [asyncapi/asyncapi#16]
AsyncAPI tries to stay close in approach to OpenAPI in terms of formats and design decisions.

There's already another issue (#1) considering serialization formats other than JSON-schema (or xml extensions). I think the payload format definition should be completely left out. OpenAPI's support for JSON-schema and xml is limiting and JSON-schema in particular is a bit messy.

There are several serialization definition formats quite more popular for message passing than json. See Avro (#1), [Google's protocol buffers](https://github.com/google/protobuf) or thrift (in its [varied protocols](https://builds.apache.org//job/Thrift/javadoc/index.html?org/apache/thrift/protocol/TSimpleJSONProtocol.html))

**Comment by fmvilas** [comment]
I understand what you mean but by removing it we would be removing value for some (most?) cases. Message headers and payload are optional so, if you don't use JSON, you can just leave it empty. However, for next versions, I'd rather add a way to specify other serialization formats, so anyone can benefit from having message definitions.

**Comment by fmvilas** [comment]
I'm closing it. Do not hesitate to comment back if needed.
