### ISSUE TITLE
[Meta] Formalise spec. review process

### ISSUE THREAD

**Issue by MikeRalphson** [asyncapi/asyncapi#165]
This is primarily a placeholder issue, as I'm not yet clear which document this should go into (e.g. CONTRIBUTING, GOVERNANCE or a new file).

I would like to propose we formalise the process of spec. reviews by representatives of AsyncAPI member / supporting organisations.

This would be in two parts.

1. Each member / supporting organisation would nominate two (*is this the right number?*) representatives to act as spec. reviewers. These can be changed at any time. They act as the core-team's points of contact for reviews and wider discussions on spec changes.
2. After each RC release of the spec, a formal review period is entered whereby all member / supporting organisation representatives are contacted and asked to evaluate the RC changes with regard to their current and planned use of AsyncAPI. Contributions to the review process from the wider AsyncAPI community are also to be encouraged and comments fed back in to the development process.

**Comment by fmvilas** [comment]
I love the idea. Thanks for writing it down, Mike!

I'd change the number to a minimum of one person, and keep two as an "ideal" number.

**Comment by rmelian** [comment]
as I am new to these committees is always my pleasure to ask the stupid questions: 
why two persons, isn't that too much? 
why not only one per each member/organization?

**Comment by MikeRalphson** [comment]
The thought with having two as the (now ideal) number is to get a consensus view rather than one person's unchecked opinion, and also (slightly contradicting that) for the cases when the main nominated person is unavailable to review during the post-RC period.
