### ISSUE TITLE
[FEATURE REQUEST] Add examples field wherever it makes sense

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#172]
This issue is about 2 things:

* Review the spec and add an `examples` field to every object where it makes sense. It should allow an array where each item is of type `any`.
* Search for `example` field and make it `examples` as the one above.

With this, we'll unify how examples are provided and align with the JSON Schema way of doing it.

**Comment by nik72619c** [comment]
Sounds great
