### ISSUE TITLE
[FEATURE REQUEST] Java code generator

### ISSUE THREAD

**Issue by gabrielps** [asyncapi/asyncapi#174]
It would be cool to have a Java code generator that could build classes given an Async API document (and maybe a serializing format: JSON, XML, ...). Do you think it is possible?

I'm surprised to be the first one asking for this :)

Cheers!

**Comment by fmvilas** [comment]
You're not, there's already a Java code generator: https://github.com/asyncapi/generator/blob/master/templates/java-spring/README.md :blush:

This repo only contains the specification. You can find more tools here: https://www.asyncapi.com/docs/tooling/.

I'm closing the issue but feel free to comment.

**Comment by gabrielps** [comment]
Ouch! Then it may be nice to update the tools page. It seems it is not listed there:
https://www.asyncapi.com/docs/tooling/#codegens

**Comment by fmvilas** [comment]
It's there. It's the AsyncAPI generator. It can generate code and documentation. But I agree it's not easy to find when you're looking for an "X language code generator".

**Comment by gabrielps** [comment]
I agree with you that its hard to find it, especially when it is stated that "**The language you’re looking for is not here**? You have created a new code generator and want to list it here? Let us know!" Thanks for your time, man!

**Comment by fmvilas** [comment]
Does it look better now? https://www.asyncapi.com/docs/tooling/#codegens

I know it's not perfect yet, but a workaround while we improve the website :)
