### ISSUE TITLE
Q: How to describe a content-based PubSub over WS

### ISSUE THREAD

**Issue by ppseprus** [asyncapi/asyncapi#182]
Hey!

On the project, I'm currently working on, we use a Confluence page to describe our WebSocket message patterns... Obviously, I love this initiative! : )

I was wondering though, how we should document our use case using AsyncApi, because we have a somewhat restricted PubSub over WebSocket.
The back end is always the publisher, while the front end is always the subscriber.
Also, the subscription is _content based_, we do not have topics.

My current AsyncApi spec looks something like this:

```yaml
servers:
  - url: host:1234
    scheme: ws

events:

  # A list of messages a consumer can send
  send:
    - $ref: '#/components/messages/subscribeMessage'
    - $ref: '#/components/messages/unsubscribeMessage'

  # A list of messages a consumer can receive
  receive:
    - $ref: '#/components/messages/publishMessage'

components:
  messages:

    subscribeMessage:
      payload:
        type: object
        required:
          - action
          - payload
        properties:
          action:
            $ref: '#/components/schemas/subscribeAction'
          payload:
            $ref: '#/components/schemas/contentObject'

    unsubscribeMessage:
      payload:
        type: object
        required:
          - action
          - payload
        properties:
          action:
            $ref: '#/components/schemas/unsubscribeAction'
          payload:
            $ref: '#/components/schemas/contentObject'

    publishMessage:
      payload:
        type: object
        required:
          - action
          - payload
        properties:
          action:
            $ref: '#/components/schemas/publishAction'
          payload:
            $ref: '#/components/schemas/dataObject'

  schemas:

    subscribeAction:
      type: string
      pattern: 'SUBSCRIBE'
      default: 'SUBSCRIBE'

    unsubscribeAction:
      type: string
      pattern: 'UNSUBSCRIBE'
      default: 'UNSUBSCRIBE'

    publishAction:
      type: string
      pattern: 'PUBLISH'
      default: 'PUBLISH'

    contentObject:
      type: object
      description: The object describing the content the client desires to subscribes to.
      properties:
        filterProp1:
          type: string
        filterProp2:
          type: string

    dataObject:
      type: object
      description: The data object, the client has subscribed to.
      properties:
        dataProp1:
          type: string
        dataProp2:
          type: string
```

I used _events_ isntead of _topics_, because the _SUBSCRIBE_ and _UNSUBSCRIBE_ events are limited to the front end, while the _PUBLISH_ is only allowed for the back end.

**And here comes the question: Is there another/better way to represent this?**

Thanks!

**Comment by fmvilas** [comment]
Hey @ppseprus! I'm glad you're asking this question. This is due to the fact that you're documenting 2 applications in a single file. That's why you're losing semantics.

You should have one AsyncAPI file for the frontend and another one for the backend. Make sure you read this article: https://medium.com/asyncapi/organizing-your-asyncapi-documents-12bccecd9ced. If this is still not enough, please don't hesitate to come back and say "hey Fran, I don't understand what the hell you're talking about!" 😝

**Comment by ppseprus** [comment]
Hey @fmvilas! Thanks for the article! It helped, however, I think I still have questions...
So.. let's say I split my API docs to two separate ones: one for the client and one for the server.
This solves the issue of generating code out of the documentation. But what I still don't know is: **is my above approach the best for the architecture I was describing?**
Based on the AsyncAPI specification, one can only subscribe to _topics_. It does not cover the scenario where I'm trying to subscribe to all **content** that matches the following predicate
```json
{
  "size": {
    "gt": 20
  },
  "shape": "circle"
}
```
How would you describe the _subscribe_ event in the _clientApi.yml_ in this case?

**Comment by fmvilas** [comment]
If I understood correctly, you want to subscribe to a set of messages that match specific filtering criteria. If that's the case, how is your code doing this? Are you sending a message to the server specifying the criteria?

**Comment by fmvilas** [comment]
If you prefer, we can discuss this better in our Slack workspace: https://join.slack.com/t/asyncapi/shared_invite/enQtNDY3MzI0NjU5OTQyLWU4ZGU2MTg1MDIyZDFjMTI2YjkxYTdlMzc1NjgzYTAxZDM1YTg1NDhhMTE2NDliMjlhZjYxNzk0ZTE5ZGU1ZTg
