### ISSUE TITLE
Offer example use cases in v2 spec introduction

### ISSUE THREAD

**Issue by jhigginbotham** [asyncapi/asyncapi#191]
Expand the introduction or add a new section after introduction that offers common use cases/solutions that AsyncAPI attempts to solve to establish common use cases (shouldn't be exhaustive). Perhaps related to #190, helping the reader to understand the common situations when asyncapi spec applies.

**Comment by fmvilas** [comment]
I'm writing documentation, use cases, and tutorials on the website. I'd keep this information out of the specification but +1 to this.
