### ISSUE TITLE
v2 spec TOC link points to the wrong location

### ISSUE THREAD

**Issue by jhigginbotham** [asyncapi/asyncapi#193]
Servers Object link in table of contents (under Schema heading) points to the wrong location. It should point to the start of the Servers section. Anchor for TOC link points to `#A2SServers` instead of `#serverObject`. 

Recommend revisiting all TOC entries to verify links point to the proper locations

**Comment by fmvilas** [comment]
This is related to #192, i.e., the lack of `Servers Object` section.
