### ISSUE TITLE
Consider v2 spec usage clarification

### ISSUE THREAD

**Issue by jhigginbotham** [asyncapi/asyncapi#196]
Per previous discussions with @fmvilas, the v2 spec is designed to account for apps that may be publishing, subscribing, or both. However, it may become a source of confusion vs. Open API Spec, as we have to consider both sides: message publisher and message subscriber. Additionally, some may only wish to capture details about message specs and available protocols, without necessarily requiring the definition to live next to the component that publishes or subscribes them. 

I would recommend some clarity (perhaps in the introduction or just after), to better establish the perspective that the spec is taking. I see two primary cases of when AsyncAPI would be used:

1. Centralized - a definition file captures the channels available for a broker using one or more protocols. AsyncAPI is used to capture message definitions and available protocols, but doesn't care what components/apps exist that are using them. This is more common for enterprise the enterprise, where governance processes desire a more channel-centric point-of-view

1. Component-oriented - definition files are created for each component that publishes and/or subscribes to a channel. These definitions may live alongside the components/apps, or centralized. References to a shared definition file with message formats are shared for maximum reusability and for mapping component/app dependencies

Let me know if this doesn't make sense and I can attempt to clarify further.

**Comment by fmvilas** [comment]
Agree this should be clarified. However, the "centralized" use case is not recommended with AsyncAPI for the reasons I explained in [this blog post](https://medium.com/asyncapi/organizing-your-asyncapi-documents-12bccecd9ced).

I'd explain that you should go for the component-oriented approach. Actually, in version 2, there's the [id property](https://github.com/asyncapi/asyncapi/blob/master/versions/next/asyncapi.md#A2SIdString) which is mandatory. This has been introduced on purpose to avoid misuse of the specification.
