### ISSUE TITLE
[FEATURE REQUEST] Relate channel parameter to payload field

### ISSUE THREAD

**Issue by jschabowsky** [asyncapi/asyncapi#199]
**Is your feature request related to a problem? Please describe.**
AsyncAPI 2.0.0/next version supports parameters in channel names which is great. But, there is no context as to where the value comes from. One of the things I see often is that the parameter is populated from the runtime event payload. If we supported noting this context, code generation could do this lifting and make the experience easier for developers. 

**Can't it be tackled using specification extensions?**
The specification needs some sort of a context field that is optional. 

**Describe the solution you'd like**
See below:
```json
{
  "user/{userId}/signup": {
    "parameters": [
      {
        "name": "userId",
        "description": "Id of the user.",
         "context": "payload" <-- add something like this, maybe an enumeration of fields
        "schema": {
          "type": "string"
        }
      }
    ],
    "subscribe": {
      "$ref": "#/components/messages/userSignedUp"
    }
  }
}
```

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fmvilas** [comment]
This is a great idea. We can probably use Runtime Expressions as we did with Correlation IDs: https://github.com/asyncapi/asyncapi/blob/master/versions/next/asyncapi.md#correlationIdObject

**Comment by fmvilas** [comment]
In case you use "context", "schema" is not needed because it will be taken directly from the definition of the payload field.

Also, pointing to a payload field makes this field mandatory in the payload or we should provide a default value.

**Comment by prdatur** [comment]
I think mandatory is the best option, In my opinion there will be much cases where no default value exists the example above shows it good. if we subscribe or publish to a channel where a "userId" is a parameter a default value would be crazy :). But, in my experience there will be definitly cases where a default value makes sense. So why not both?

```
parameters:
  userId:
    type: String
    default: 4
```

If a default value is provided it will be used if nothing was provided, if the default value definition does not  exists, the parameter becomes mandatory, maybe but only maybe a definition of optional: true without a default value can make the parameter optional?

**Comment by fmvilas** [comment]
Note to myself: check out #255 before starting to work on this issue.

**Comment by jasonmac01** [comment]
+1 using a runtime expression here would be a great idea. We're having similar discussion on runtime expressions for selecting entire payloads. Applying them to parameter extraction within a Channel key would be great.
