### ISSUE TITLE
Description for topics

### ISSUE THREAD

**Issue by marcortw** [asyncapi/asyncapi#207]
I'm new to asyncapi and I'm not sure if my issue is just non-sense, but I'll give it a try.

**Is your feature request related to a problem? Please describe.**
I have only a handful of generic topics, composed of variable names. I am using relatively complex messages and I wanted to describe the topic itself in a generic way, before the actual variables are described. This doesn't seem to be possible at the moment. The 'topicItem' definition only allows 'parameters', 'publish', 'subscribe' and 'deprecated'

**Can't it be tackled using specification extensions?**
It could be done with an extension, but I thought that others might want to put a little description below a topic too.

**Describe the solution you'd like**
Just add something like this to the topicItem.properties schema definition:
`
"description": {
          "type": "string",
          "description": "A short description of the topic."
        }
`

**Describe alternatives you've considered**
I tried to use $ref, but the topicItem structure seems to be magically enforced nevertheless:

```
topics:
  my/{variable}/topic:
      $ref: "#/components/schemas/topicDesc"
...
components:
  schemas:
    topicDesc:
      description: asdf
```

**Additional context**
n/a

**Comment by fmvilas** [comment]
You're totally right. I'm labeling it as v2.0.0 feedback because v2.0.0 neither has it.

Would you like to solve this issue? I can always point you in the right direction.

**Comment by marcortw** [comment]
Thanks for the quick reply. I'd like to try to implement this with a PR if you could point me to the files which might need a change. PR to master?

**Comment by fmvilas** [comment]
Absolutely, these are the files:

* https://github.com/asyncapi/asyncapi/blob/master/versions/next/asyncapi.md#channelItemObject
* https://github.com/asyncapi/asyncapi/blob/master/versions/next/schema.json#L557

Create a PR pointing to master. You might want to add the description property to some of the examples but it's not strictly necessary.

Thanks!
