### ISSUE TITLE
[2.0.0 REVIEW] Headers may have to be a schema

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#210]
In version 1.x, message property `headers` is a schema. This has been replaced by a map of keys where each of the keys must be a schema. However, this structure doesn't allow us to define something like "these are my headers and additional ones should not be permitted". Probably the solution is to make `headers` a schema again but enforce that it should be of type "object". This way we can enforce things like the ones described previously.

**Comment by marcortw** [comment]
If you'd put it back into a schema then I assume the following would work?

```yaml
components:
  messages:
    tstCmdMsg:
      name: tstCmdMsg
      summary: A *command* message.
      contentType: application/json
      description: Commands are sent as an instruction to do something
      headers:
        $ref: '#/components/schemas/tstHeader'
      payload:
        type: object
        properties:
          test:
            type: string
[...]
  schemas:
    # HEADER Definitions
    tstHeader:
      type: object
      required:
        - headerA
      properties:
        headerA:
          $ref: '#/components/schemas/headerA'
        headerB:
          $ref: '#/components/schemas/headerB'
        headerC:
          $ref: '#/components/schemas/headerC'
```
What actually works for me is to repeat the headers for each message as you can see below. However, I can't define `additionalProperties: false` for the `headers:`. I guess it's because of the same reason, headers not being a schema?

```yaml
components:
  messages:
    tstCmdMsg:
      name: tstCmdMsg
      summary: A *command* message.
      contentType: application/json
      description: Commands are sent as an instruction to do something
      headers:
        headerA:
          $ref: '#/components/schemas/headerA'
        headerB:
          $ref: '#/components/schemas/headerB'
        headerC:
          $ref: '#/components/schemas/headerC'
        additionalProperties: false
      payload:
        type: object
        properties:
          test:
            type: string
```
As you can see, I'd like to reuse the same header fields for different messages.

Kind regards,
Marco

**Comment by fmvilas** [comment]
Correct. It's exactly that reason. I'll try to have it for 2.0.0-RC2.

**Comment by marcortw** [comment]
That would be very helpful for me and, I assume, for other users too. Thank you!
