### ISSUE TITLE
[2.0.0 REVIEW] Use JSON Schema Draft 07 as the default schema

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#212]
After playing a lot these days with AsyncAPI 2.0.0-rc1, I realized most of the pain comes from having the OpenAPI schema as the default. We want to keep supporting OpenAPI schemas but there's no need to make it the default choice.

There's only one thing that worries me and it's the lack of a deprecation property in Draft 07. However, @philsturgeon is working on it and will probably make it for Draft 08. As per `discriminator` and `externalDocs`, they can just be extensions in the form of `x-discriminator` and `x-external-docs`. Same for `deprecated` in the meantime, it can be done using `x-deprecated`.

@handrews do you have a list of changes (or potential changes) for Draft 08? I've seen [this](https://github.com/json-schema-org/json-schema-spec/milestone/6) but I'd like to know if upgrading the AsyncAPI default schema from Draft 07 to Draft 08 will be a breaking change. Or put it another way, are there breaking changes in Draft 08 compared to Draft 07?

**Comment by philsturgeon** [comment]
`deprecated` got merged (albeit a bit hastily) into draft 08 so you're all set.

**Comment by fmvilas** [comment]
Awesome!! 🎉 And congrats for your first contribution on JSON Schema, Phil.

**Comment by fmvilas** [comment]
@philsturgeon I'm going to (almost) follow your suggestion here: https://github.com/OAI/OpenAPI-Specification/pull/1977.

However, and since tooling is not yet ready for Draft-08, AsyncAPI is going to adopt a superset of Draft-07 as the default schema, and the parser will provide a "translator" from current OpenAPI schemas.

Thanks for the work you did there. It helped clarify the current scenario.

**Comment by philsturgeon** [comment]
![giphy-downsized-large](https://user-images.githubusercontent.com/67381/62717690-a6a55780-ba04-11e9-89f8-7a9be73bc96c.gif)
