### ISSUE TITLE
[FEATURE REQUEST] Support custom scheme field values in server object.

### ISSUE THREAD

**Issue by vadeg** [asyncapi/asyncapi#214]
**Is your feature request related to a problem? Please describe.**
[Server Object](https://github.com/asyncapi/asyncapi/blob/master/versions/1.2.0/asyncapi.md#server-object) has a `scheme` field (which will be renamed to `protocol` in version 2) which supports only limited amount of protocols. The problem is that there are custom protocols exist which are not covered by specification. In case of custom protocol defined it is impossible to generate API html or any other view because of error.

**Can't it be tackled using specification extensions?**
`scheme` field is a mandatory field in specification and can not be replaced with extension. 

**Describe the solution you'd like**
The solution is to make `scheme` field required in specification but not limited to specific list of values. It will allow to define custom protocols in API. 
Also, it will "release" specification from implementation details. Current implementation requires to create new specification version with every new supported protocol.

**Describe alternatives you've considered**
I have not found any alternative solutions.

**Additional context**
We are using custom event bus built on top of another popular open source event bus solution. The custom solution have a custom protocol implemented. We would like to use Async API specification to describe service API. Unfortunately, it is not possible due to `scheme` field limitation.

**Comment by fmvilas** [comment]
Hey @vadeg! It's great to see you came to the same conclusion as us. It's already implemented in version 2.0.0-rc1. Check it out: https://www.asyncapi.com/docs/specifications/2.0.0-rc1/#serverObject.

We're close to releasing a new version of the [AsyncAPI generator](https://github.com/asyncapi/generator/pull/51) that supports AsyncAPI 2.0.0-rc1. This will allow you to generate documentation and code.

Would you like to participate in the beta test? That would be very helpful for us.

**Comment by vadeg** [comment]
Hi @fmvilas . 
Good news!
Yes, I would like to participate in the beta test.

**Comment by fmvilas** [comment]
Awesome! Can you please send me an email to fmvilas at gmail.com? It's just so that I can send the details whenever the beta is ready for sharing.
