### ISSUE TITLE
[2.0.0 REVIEW] From Kyma for AsyncAPI with love 

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi#221]
# AsyncAPI Review Document

|Project name|Reviewers|Company|Spec version|
|------------|---------|-------|------------|
|Kyma|@derberg, @magicmatatjahu|SAP|v2.0.0|

## Our goals with this project are to:
  1. Have one consistent way of specifying all the event types that can come from a single application
  2. Use spec as documentation and as an input for event registry for developers that want to consume messages but do not know what messages are out there and how they look like

## We expect to:
  1. Have what we had with 1.0 because for now our users approach asyncapi in the way that they generate it from code, so the do not need to many features, like `components`

### 1. We think `Id` should not be mandatory
We do not find any value in this information as we treat spec as a doc with set of info, and it is referenced by external `Id`, we can generate it and add but that would be a dummy operation only. 

#### We think it can be solved by...
just make it optional but anyway we see it is addressed here https://github.com/asyncapi/asyncapi/issues/219

#### Overall, we think this challenge/difficulty is...
  * [X] A "nice to have".
  * [ ] A blocker for us to adopt this version of the spec.
  * [X] Something that doesn't affect the specification.

## Other thoughts?

We think 2.0 is a good direction, like introduction of the security information to access the broker https://www.asyncapi.com/docs/getting-started/security/

I only had some struggle with glossary, being with Kyma in between AsyncAPI and Knative with all those different glossaries I had to get used to switching names in my head. EventTypes that I know from Knative and Kyma are in AsyncAPI channels if I understand correct, while in Knative channels are different things https://knative.dev/docs/eventing/channels/. This is just a side comment as I don't think we can do something about really

---
_AsyncAPI Initiative — (website: [asyncapi.org](https://asyncapi.org), twitter: [@AsyncAPISpec](https://twitter.com/AsyncAPISpec))_

**Comment by fmvilas** [comment]
Thanks for reviewing, @derberg and @magicmatatjahu! As you said, there's little we can do with naming because then other people in other contexts would complain about it too. Actually, that was the reason we switched from topics to channels, so our naming "collides" a bit less.

Greatly appreciate you took the time. Thank you! 🙌
