### ISSUE TITLE
[2.0.0 REVIEW] An application is not an API in EDA

### ISSUE THREAD

**Issue by scottvorthmann** [asyncapi/asyncapi#223]
# AsyncAPI Review Document

|Project name|Reviewers|Company|Spec version|
|------------|---------|-------|------------|
|internal project|@scottvorthmann|TIBCO|v2.0.0|

## Our goals with this project are to:
  1. Use AsyncAPI docs to generate application code stubs, for both publishers and subscribers
  2. Use AsyncAPI docs as configuration artifacts for generic publisher/subscriber implementations

## We expect to:
  1. document an event stream, rather than a subscribing or publishing application
  2. avoid redundant configuration for participating applications

### 1. AsyncAPI favors bottom-up approaches

An API, by any reasonable definition, is a contract that allows multiple applications (using the terminology of AsyncAPI) to successfully interact.  In the REST or client-server world, any such contract is very strongly oriented: the service provider defines the contract, and service consumers either adhere to it or fail.

In an event-driven architecture, the focus shifts from away from any single application.  The contract that must be defined is simply what kind of messages/events are flowing, and where.  Applications can participate either by publishing or by subscribing, and no single application owns the contract.

The current formulation of AsyncAPI does not really support this idea of a contract standing apart from any single application.  AsyncAPI today documents the behavior of a single application, unnaturally forcing a provider-consumer orientation on the contract.  In a scenario with multiple publishers and multiple subscribers using a given channel, each application's AsyncAPI specification will look essentially identical to all the others, differing only in identification and in the "publisher" or "subscriber" keyword.  This redundancy is immediately evident in the "Getting Started" examples, and is only weakly addressed by extracting the message declaration in a standalone document; the redundancy of server and channel remains.  I feel that the redundancy is to be addressed not by adding more reuse features, but by fundamentally shifting the API definition away from any particular application, at least as a possibility.

#### We think it can be solved by...

...merging the fields of the operation object into the channel item object.  Furthermore, where the channel item object had either a "subscribe" or a "publish" operation object, instead it now has an additional optional "role" field whose value must be "publish" or "subscribe".  If the role is absent, then the channel is documenting itself, rather than an application documenting its role with respect to a channel.

~~~yaml
asyncapi: '2.0.0-rc2b'
id: 'urn:hello-world-app'
info:
  title: Hello world application
  version: '0.1.0'
servers:
- url: broker.mycompany.com
  protocol: amqp
  description: This is "My Company" broker.
channels:
  hello:
    role: subscribe
    message:
      payload:
        type: string
        pattern: '^hello .+$'
~~~

#### Overall, we think this challenge/difficulty is...
  * [x] A "nice to have".
  * [ ] A blocker for us to adopt this version of the spec.
  * [ ] Something that doesn't affect the specification.

## Other thoughts?

I have noted this issue as a "nice to have", since we can readily address the concerns simply by ignoring the "publisher"/"subscriber" key in a channel.  Nonetheless, I feel this is a fairly profound difference in conceptual terms.  To us, an EDA "application" is a larger thing, corresponding to a collection of applications in the AsyncAPI sense; all the processes are integrated as a single application by virtue of coordinating around the event channels and the messages on them.  This is a top-down use of AsyncAPI, and should be just as naturally supported as the bottom-up use.

---
_AsyncAPI Initiative — (website: [asyncapi.org](https://asyncapi.org), twitter: [@AsyncAPISpec](https://twitter.com/AsyncAPISpec))_

**Comment by fmvilas** [comment]
Thanks for the review, Scott! As we spoke, this will not make any changes in the spec, hence I'm closing it.
