### ISSUE TITLE
[2.0.0 REVIEW] Unclear / odd semantics of multiple servers

### ISSUE THREAD

**Issue by scottvorthmann** [asyncapi/asyncapi#224]
# AsyncAPI Review Document

|Project name|Reviewers|Company|Spec version|
|------------|---------|-------|------------|
|internal project|@scottvorthmann|TIBCO|v2.0.0|

## Our goals with this project are to:
  1. Generate publisher/subscriber code stubs from AsyncAPI docs
  2. Configure generic publisher/subscriber code using AsyncAPI docs

## We expect to:
  1. have a clear interpretation to apply when there are multiple servers specified

### 1. current QA/prod/dev motivation makes no sense

In a bottom-up scenario, where we are documenting the behavior of a single application, that application is running in a single environment, not three.  By analogy, would you use Swagger to try to record three different hosts for a REST endpoint?  It seems odd to me to use AsyncAPI to document one's development lifecycle or CI/CD pipeline.  In a bottom-up use-case, only one server needs to be recorded, the one actually in use by the application. 

In a top-down scenario, where we wish to generate code from an AsyncAPI document, the code generator is likely to ignore the server URL in any case, since such configurations would typically be late-bound via dependency injection anyway.  If there are multiple protocols offered, the code generator will have to choose, and possibly in a constrained way based on available APIs.  I can imagine this implying that a channel is being bridged across different technologies / protocols.

#### We think it can be solved by...

... removing the notion of multiple servers, or motivating it with a more sensible use-case, e.g. protocol bridging.

#### Overall, we think this challenge/difficulty is...
  * [x ] A "nice to have".
  * [ ] A blocker for us to adopt this version of the spec.
  * [ ] Something that doesn't affect the specification.

---
_AsyncAPI Initiative — (website: [asyncapi.org](https://asyncapi.org), twitter: [@AsyncAPISpec](https://twitter.com/AsyncAPISpec))_

**Comment by fmvilas** [comment]
Thanks for the review, Scott! As we spoke, this will not make any changes in the spec, hence I'm closing it.
