### ISSUE TITLE
[2.0.0 REVIEW] Clarification on Channel naming

### ISSUE THREAD

**Issue by jasonmac01** [asyncapi/asyncapi#237]
The [Channels](https://www.asyncapi.com/docs/specifications/2.0.0-rc1/#a-name-channelsobject-a-channels-object) object mentioned that Channel keys must start with a "/" or be relative to the server's `baseChannel` - This may be a bit ambiguous in situations where the `baseChannel` is not provided (defined as defaulting to "empty string"). I would thus assume the key is relative to "/" - effectively, treating it as an absolute path. Perhaps this can be clarified in this description block?

Additionally, a total nit-pick... Consider changing "base channel" to "baseChannel," perhaps? It makes searching of the page easier to find all references.

**Comment by fmvilas** [comment]
Hey Jason! Thanks for the review and suggestion. `baseChannel` will be removed as it's causing too many ambiguities.

**Comment by sergeytsivin** [comment]
Hi! How do we deal with the constraints that some message brokers imply? For instance Kafka topic names are limited to the following chars "[a-zA-Z0-9\\._\\-]". So Kafka doesn't allow forward slashes in topic names.

**Comment by derberg** [comment]
@sergeytsivin in code generation we just transform them into proper, broker compatible names, basing on the information about the server protocol provided in Server object
