### ISSUE TITLE
Mistake in 'Channel Item Object Example'

### ISSUE THREAD

**Issue by Tobjoern** [asyncapi/asyncapi#275]
The yaml code of the channel item does not match the JSON version, as the 'bindings' key is missing, and as per the specification is required for protocol specific infromation.

JSON version:
```
  "bindings": {
    "amqp": {
      "is": "queue",
      "queue": {
        "exclusive": true
      }
    }
  }

```

Yaml version:
```
amqp:
  is: queue
  queue:
    exclusive: true
```
I have fixed this mistake here: https://github.com/Tobjoern/asyncapi and I will submit a pull request, as soon as this issue is approved.

**Comment by fmvilas** [comment]
Thanks for reporting, @Tobjoern. Coincidentally, @olvlvl fixed it in #276.
