### ISSUE TITLE
Slack invite link is expired

### ISSUE THREAD

**Issue by alex-dodich** [asyncapi/asyncapi#277]
Hi! 
Could you please renew slack invitation link?
![Screenshot from 2019-10-02 17-31-09](https://user-images.githubusercontent.com/38131302/66053758-8fce3d80-e53b-11e9-86fd-900fc43624e5.png)
PS: Sorry,  i've accidentally added wrong label for this issue

**Comment by fmvilas** [comment]
Oops! This link should never expire. Anyway, It's updated on the website. Thanks for reporting!

**Comment by fmvilas** [comment]
It's now updated on the repo too. Thanks!

**Comment by alex-dodich** [comment]
Thank you!
