### ISSUE TITLE
Definition of bindings needs clarification

### ISSUE THREAD

**Issue by jstoiko** [asyncapi/asyncapi#283]
In AsyncAPI 2.0, the server/channel/operation/message bindings can be either "fixed" or custom via `x-` extension. The "fixed" set of bindings are all defined in [asyncapi/bindings](https://github.com/asyncapi/bindings). That part is clear. 

The part that is confusing in the spec is that the description of each type of binding starts with `A free-form map...`. However, if it's "free-form", it cannot by definition be "fixed". It also clashes with some of the "fixed" bindings described in  [asyncapi/bindings](https://github.com/asyncapi/bindings) which disallow the use of certain types of bindings. E.g. for `amqp`, `server` bindings are [disallowed](https://github.com/asyncapi/bindings/tree/master/amqp#server-binding-object) altogether.

**Comment by fmvilas** [comment]
You're right. Bindings need more love. What do you propose we should do?

**Comment by jstoiko** [comment]
I would remove the term `free-form` from all `bindings` descriptions and I would add the sentence `This object can be extended with Specification Extensions.` at the end of each server/channel/operation/message bindings sections.
