### ISSUE TITLE
[FEATURE REQUEST] Support Parameter formats

### ISSUE THREAD

**Issue by raveclassic** [asyncapi/asyncapi#294]
**Is your feature request related to a problem? Please describe.**
Currently `ws` channel bindings allow you to define some query/header parameters: https://github.com/asyncapi/bindings/tree/master/websockets#channel-binding-object
However this solution lacks flexibility and power in comparison to [swagger-2](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object) or [openapi-3](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameter-object) parameters. Especially in case of non-primitive parameters - there's no way to define how such parameters should be serialized. Swagger-2 spec has a `collectionFormat` and `openapi-3` - `style`/`explode` for that.

**Can't it be tackled using specification extensions?**
IMO this should be part of the core spec.

**Describe the solution you'd like**
The best would be to replicate `openapi-3` approach to describe parameters using `in`/`style`/`explode` (etc.) properties.

**Describe alternatives you've considered**
Not sure there're some which would allow the same level of flexibility and consistency.

**Additional context**
I'm writing a codegen tool based on `swagger-2`/`openapi-3`/`asyncapi-2` specs which automatically handles connections that's why I need a solution to fully handle parameters.

**Comment by fmvilas** [comment]
Issue moved to [asyncapi/bindings #8](https://github.com/asyncapi/bindings/issues/8) via [**ZenHub**](https://www.zenhub.com/)

**Comment by fmvilas** [comment]
This issue belongs to the WebSockets binding, so I've moved it there.
