### ISSUE TITLE
Outdated README for version 2.0.0 examples

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#299]
The README of the 2.0.0 examples hasn't been updated with the release: https://github.com/asyncapi/asyncapi/blob/master/examples/2.0.0/README.md. We should update accordingly or remove it.

**Comment by derberg** [comment]
I think that the best option would be just to remove the Readme. This directory just contains a list of examples with filenames that are pretty clear, so readme is unnecessary

**Comment by fmvilas** [comment]
Agree.
