### ISSUE TITLE
sample.yml has textual termsOfService not a URL as per spec

### ISSUE THREAD

**Issue by MikeRalphson** [asyncapi/asyncapi#30]
https://github.com/asyncapi/asyncapi/blob/develop/test/docs/sample.yml#L9

> You can specify the terms of service here. **It supports Markdown as well.**

Should be

> A URL to the Terms of Service for the API.

OpenAPI 3.0.0 adds to the field description:

> MUST be in the format of a URL.

**Comment by fmvilas** [comment]
Oh, good catch. Thanks man will fix soon.

**Comment by fmvilas** [comment]
@MikeRalphson it's now fixed. Thanks again.
