### ISSUE TITLE
API documentation strategies

### ISSUE THREAD

**Issue by kvaleev** [asyncapi/asyncapi#300]
## Background

I'm aware that it's proposed not to use a single AsyncAPI specification for all the channels and messages (although it's not in the official documentation, but [in a blog post](https://medium.com/asyncapi/organizing-your-asyncapi-documents-12bccecd9ced)). 

However, it's still not clear how the AsyncAPI specification should be maintained. I consider two options, one of each is _recommended_ and one is not, but I still have issues on the exact specification strategy.

### 1. Having a specification file per application

Create a bunch of AsyncAPI specs for all the applications that exchange messages (and there can be a lot of them if we speak about the microservice pattern) and a common part that is reused between them (with servers, messages, and so on). 

This approach definitely solves the purpose of describing each individual microservice, but I have several other issues with it:

1. Lack of single API documentation. We have a bunch of different specs documentation sites hosted for every application which is difficult to navigate.
2. There is no documentation of all available channels and messages. So when we design a new service there is no place to go and choose the channels and messages it could use.

### 2. Having a single specification for the whole API

In opposite to the first approach, this one is more close to the traditional API schema design. It provides a single place to discover and get details about all topics available within the system. And of course, it has its flaws as well:

1. Unclear usage of `subscribe`/`publish` fields. When we focus on the channels and messages, and not on consumers and publishers, having these mandatory fields in a `channel` description looks redundant and confusing. I.e., if there is a channel/message, there always be someone who publishes it, and someone who subscribes to it – so, all the channels have to have both of these parameters which currently don't add any meaning to it.
2. Unlike the first approach, this one doesn't provide any information about services that use the API, so it focuses only on API itself and not its usage.

## Suggestions

1. Add some explanation to specification strategies to the official documentation.
2. If the second approach (unified API spec) is considered permissible (even if not encourage) add some advice on how to deal with `subscribe`/`publish` fields in this case to the official documentation.
3. _AsyncAPI specification improvement suggestion_: what if additional fields `consumers` and `publisher` that can be added to channels in the same way as `tags` for instance. In this manner, we can still have a unified API spec and get the idea of applications that use it, at the same time.

**Comment by kvaleev** [comment]
Relevant discussion, I guess: https://github.com/fmvilas/asyncapi-examples/issues/1

**Comment by kvaleev** [comment]
@fmvilas, if it's needed to have single documentation for all channels, the most reasonable way is just to add both `subscribe` and `publish` operation objects for every channel, am I right?

**Comment by fmvilas** [comment]
Hey Konstantin! Thanks for the thoughtful analysis and suggestions. Let me answer them:

> 1. Add some explanation to specification strategies to the official documentation.

We're on this. Even simply coordinating contributions is a lot for me right now so I'm happy to say that there will be a person in charge of the docs (and community) soon.

> 2. If the second approach (unified API spec) is considered permissible (even if not encourage) add some advice on how to deal with subscribe/publish fields in this case to the official documentation.
> 3. AsyncAPI specification improvement suggestion: what if additional fields consumers and publisher that can be added to channels in the same way as tags for instance. In this manner, we can still have a unified API spec and get the idea of applications that use it, at the same time.

We considered this option back in time but _a file per app_ approach was preferred. The reason is that it makes the file more granular and specific. Also, adding a new application would not require touching a centralized file. In the end, the discussion is very similar to monolith vs microservices. Monoliths (single file) are very convenient but hard to scale and manage. Microservices (multiple files) are easy to scale and manage (at least individually) but require more tooling and processes to work with them.

I'm not saying the current approach is the best. It will always depend on your use case and fore sure we need more documentation and tooling to make things easier :)

**Comment by kvaleev** [comment]
Thank you for your answer, Fran! I see the point in having a _specification file_ per app and how it makes the whole API easier to maintain. However, I would like to discuss a slightly different topic: the generation of a single _documentation view_ for all these files.

If we have _specification per app_ does it mean that we need to have several documentation views for all these specifications? So there should be literally dozens of individually hosted web sites with different URLs for every application specification, and no single reference with all of them?

I consider it rather useful to have a single reference for all channels and messages in the system. With OpenAPI you can make it using `$ref` or even via some custom preprocessing. With AsyncAPI it becomes a little messy with `subscribe`/`publish` fields, as they are associated not with the API itself, but rather with the applications that use it – so they not about the interaction contract, but more about the system structure.

So, currently, if we still want to have a single documentation view (aggregation of all application specification), I see the options:

1. Don't use `subscribe`/`publish` fields at all (which is actually not an option as it violates the syntax).
2. Use only `subscribe` or `publish`(which one? any?).
3. Use both of them.

I lean towards the third one, even it implies some redundancy. But maybe there is a better way?

**Comment by kvaleev** [comment]
@fmvilas, what do you think?

**Comment by fmvilas** [comment]
Oh, I hear ya. Yes, a single view of multiple files (a developer/API portal) would be useful. I'm currently working on a solution for that. Check out [asyncapi.stream](https://asyncapi.stream). The landing page is a bit out of date and might not reflect exactly what we're working on but you get an idea.

**Comment by kvaleev** [comment]
> Check out asyncapi.stream.

Looks promising. So, you just don't render `subscribe`/`publish` on this API documentation portal, do you?

**Comment by fmvilas** [comment]
It's still a work in progress but the idea is that you get a combination of 2 things:

1. Overview of your architecture with publishers, subscribers, channels, messages, etc.
2. You can also get a view of a specific API.

It's still draft and design will change overtime for sure.
