### ISSUE TITLE
Register boats as a DSL language tool for asyncapi

### ISSUE THREAD

**Issue by johndcarmichael** [asyncapi/asyncapi#324]
I wrote BOATS a little while ago for swagger/OpenAPI projects.

https://www.npmjs.com/package/boats
https://johndcarmichael.github.io/boats/#/

Recently started working with rabitmq and picked up asyncapi so it seemed a good fit to extend boats to work with asyncapi as well as openapi.

**Comment by derberg** [comment]
@johndcarmichael Hey man, awesome news!
Boats uses Nunjucks ❤️ 
I just recently wrote about it [here](https://www.asyncapi.com/blog/using-nunjucks-with-asyncapi/). We use it in the [generator](https://github.com/asyncapi/generator/) project.

If you want you can add this tool [here](https://www.asyncapi.com/docs/tooling/) (source is [here](https://github.com/asyncapi/website/blob/master/content/docs/tooling.md))

**Comment by derberg** [comment]
@johndcarmichael maybe consider also joining this slack apisyouwonthate.slack.com where community also shares and asks for feedback on tools built for OpenAPI

**Comment by derberg** [comment]
@johndcarmichael  PR is merged https://github.com/asyncapi/website/pull/59 and already published https://www.asyncapi.com/docs/tooling/#dsl

I also added it to the draft of our newsletter https://docs.google.com/document/d/1vGZ1e8zxPxSXu0r5457Vohb9hjg8hkvolWSOFjr73-Y (you need to join this group to see the doc https://groups.google.com/forum/#!forum/asyncapi-users). We will send out newsletter on Thursday, you can signup to get it if you want https://www.asyncapi.com/subscribe/

Thanks a lot for the contribution! Is there anything else here or we are closing this one?

**Comment by johndcarmichael** [comment]
You move fast :) nothing to add from my end

**Comment by derberg** [comment]
![](https://media.giphy.com/media/37nHk9ifP7no2dynFB/giphy-downsized.gif)
