### ISSUE TITLE
[FEATURE REQUEST] Improve specification/description of applicationInstanceId property

### ISSUE THREAD

**Issue by peraxelson** [asyncapi/asyncapi#360]
**Is your feature request related to a problem? Please describe.**
Background: 
I'm implementing an internal AsyncAPI and the plan is to use both correlationID and applicationInstanceId in a payload header. correlationId is fairly well specified in the documentation but applicationInstanceId is less so. Is there a best practice concerning applicationInstanceId?
We're considering using urn's to define our different applications/services in our system.

The intention is to use the applicationInstanceId to identify the service that has published a request on an api to be able see when and who requested a change. As an example we want to know if a user has stopped the system via the webpage or if someone has pressed the stop button on the local touch screen. Both the webpage and the touch screen published the request to the "system state" API. As there are several users that can stop the system from the webpage it would also be useful to have each publisher send additional info on which user has requested the stop. 

**Can't it be tackled using specification extensions?**
possibly but it would be good to have a general best practice.

**Describe the solution you'd like**
Have the applicationInstanceId use uri format. As per fmvilas example:
```
asyncapi: 2.0.0
info:
  title: Test
  version: 0.1.0
channels:
  user/signedup:
    publish:
      message:
        headers:
          type: object
          properties:
            applicationInstanceId:
              type: string
              format: uri
        payload:
          type: object
```
Examples: 
“uri:company-name:cloud:10" ->Request was initiated by userId 10 on the cloud
“uri:company-name:display" ->Request was initiated by pressing a button on the touchscreen

**Additional context**
We have APIs on several levels so using an uri-type format would be good to have

**Comment by fmvilas** [comment]
Hey @peraxelson! Thanks for your patience (almost a year after! 😅). I just noticed this issue today. The `applicationInstanceId` example is just for illustration purposes, it doesn't have any special meaning in AsyncAPI. It's not even defined by the spec. That said, what you did in your proposal is totally fine and I think you should continue using it. I'm closing this but feel free to leave a comment if I misunderstood your idea. Thanks!
