### ISSUE TITLE
Conference promotion

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi#369]
Once we have agenda published on Wednesday, we should promote our event not only on our social media channels but also:

1. Ask owners of Newsletters of communities that we know in they can promote the event and in exchange, we will place their logo and link to their website on our event landing page (so called media partners) - 💯 
1. Feature conference in our Newsletter - 💯 
1. Share on Hacker News and ask community to vote-up - 💯
1. Share on Reddit in programming channel and ask community to vote-up - 💯
1. Write Asyncapi blog post and Write dev.to blog post  💯 
1. Share on Facebook groups we know exist around our topic - 💯

**Comment by MikeRalphson** [comment]
Submit to https://webapi.events/ ?

**Comment by derberg** [comment]
Additional resources from @Mrc0113
- https://cfpcalendar.com/
- https://confs.tech/ 

After digging into source code of https://cfpcalendar.com/ I noticed some more:
- https://seecfp.com/
- https://sessionize.com/
- https://www.papercall.io/

I'll explore how many we can still use and which are already a lost case as CFP is closed

**Comment by derberg** [comment]
We are already listed here https://www.cfpland.com/conferences/rectjZRJ8OKn3VGfj/

**Comment by derberg** [comment]
- Hacker News and Reddit I leave for a moment when we will have a schedule ready.
- PR to https://confs.tech/ created

**Comment by derberg** [comment]
we are listed here https://dev.to/listings/events/the-first-asyncapi-conference-free-online-2020-04-22-pg4 thanks to @MikeRalphson

**Comment by derberg** [comment]
we got just mentioned by locla Polish meetup around Go and Cloud Native -> https://www.facebook.com/GophersSilesia/photos/a.560245014341319/1100087733690375/?type=3&theater

**Comment by derberg** [comment]
Sent email to contact@cooperpress.com that is behind few Twitter accounts and newsletters.

Blog post about conference released and promoted on usual platforms, Dev.to, HackerNews and reddit -> https://news.ycombinator.com/item?id=22822118

**Comment by derberg** [comment]
I ran out of ideas where else to write, so last step is to introduce a Media Partners section on conference page to mention few groups that wrote about us

**Comment by derberg** [comment]
Media Section added -> https://www.asyncapiconf.com/#media-partners
