### ISSUE TITLE
Conference sponsorship

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi#372]
## Why we need sponsors

1. We want to share with the community engaged in the conference (speakers and others) discount so they can get for free something from our online shop https://asyncapi.threadless.com/. Community is first as we are able to do this crazy event in a short time thanks to people's engagement.
1. Paid event marketing like Twitter Ads and other similar

After the event, we will transparently share all the expenses.

### Corporate/Company/Organization

**200$** Silver sponsor
- Logo of the company with a link to the website featured on our conference website
- Logo of the company with a link to the website tweeted from our official Twitter account
- Sponsors listed in a summary blog post about the event

**300$** Golden sponsor
- All the above
- Sponsors listed in our newsletter to our subscribers where we will send a memo after the event with short summary and a link to the blog post
- Sponsor is always mentioned before every talk
- During breaks, in the conference stream, we will display a slide with all the sponsors listed. Separate slide with Golden & Platinum sponsors only

**600$** Platinum sponsor
- All the above
- Sponsors will be there visible live and in the recording that will be available on YouTube. Example is here https://www.youtube.com/watch?v=XmSK1t0w1L8&t=1025s 

Whenever the logo of the sponsor is mentioned, the size will depend on the size of the contribution.

### Individual

Any contribution amount will be welcome 🙏

- Name of the contributor with a link to the website listed on our conference website
- Sponsors listed in a summary blog post about the event
- During breaks, in the conference stream, we will display a slide with all the sponsors that donated more than 50$. In other words, a separate slide with individual contributors listed.
- 50$ sponsors will be there visible live and in the recording that will be available on YouTube (because of the previous point as they will be on the slide that will stay in the recording)

## How to become a sponsor
👉 [Go to Open Collective event's page](https://opencollective.com/asyncapi/events/asyncapi-online-conference-fd574661)

**Comment by fmvilas** [comment]
I just added the link to the Open Collective event's page.

**Comment by derberg** [comment]
Most of the communication to potential sponsors that we know sent out

**Comment by derberg** [comment]
Sponsorship is organized, first sponsor is already there and features in our website
