### ISSUE TITLE
AsyncAPI open meeting, Tuesday Apr 28 2020

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi#375]
This is the meeting for the AsyncAPI Special Interest Group (SIG). You're invited to [join us](https://zoom.us/j/165106914) and ask questions. **The meeting takes place on alternate Tuesdays at 6 pm CET**. Recordings from the previous meetings are available in [this](https://www.youtube.com/watch?v=S8gvf0XjO10&list=PLbi1gRlP7pijUwZJErzyYf_Rc-PWu4lXS) playlist on YouTube.

If you want to make proposals for the specification and/or the tooling, please reach out in our [Slack workspace](https://www.asyncapi.com/slack-invite) or just leave a comment below.

Join [this](https://groups.google.com/forum/#!forum/asyncapi-users) mailing list to get an always-up-to-date invite to the meeting in your calendar. 

## Attendees

> Join us if you want to know more about AsyncAPI! The meeting is open to the public.

## Agenda

>Don't wait for the meeting to discuss topics that already have issues. Feel free to comment on them earlier.

1. Q&A
1. _Place for your item_
1. Conference summary in numbers
1. Meeting time options to be much more friendly to APAC
1. [Contributor guide - what do you need?](https://docs.google.com/document/d/1uWGDOkeT9J4acD7rPge468Tme0OotynldsXqtpuGTD8)
1. New important features in Generator
1. Q&A

## Meeting notes

> Conference summary in numbers

We will for sure summarize the whole event, including stats in a single blog post but for now, we can share what we quickly extracted from YouTube Analytics

```
#numbers checked around 10AM UTC 28.04
2,772 views in total

## During event:
- 750 chat messages
- 288 concurrent users
- between 200-100 (slowly dropping) during the last 2hours -> next time 5h event? or was it because it was after 6PM and Europe was already focused on a private life?

## After event (organic, not doing paid tweets yet):
- around 1000 unique views in a week after publishing recording
- people spend with recording on average 30min -> length of one talk
- most attention (so what parts of the video are watched the most) goes to Norberto -> Kin -> Marc
```

> Meeting time options to be much more friendly to APAC

As Paul brought to our attention in the comments on this issue - we should open ourselves for the other side of the globe. The easiest approach is to do the meeting in early Europe hours and then again late, then early, and then late, then early and then late (I think you know where it is going 😄)

@Paul-T-AU next meeting, 12.05 come and invite others from APAC as we start at [8AM UTC](https://everytimezone.com/s/9c9d6256) !

We think it should be fine for the community as meetings are anyway recorded. In case we see issues we will adapt, and we can spy on CNCF and others, how they solve time zone issues. 

> [Contributor guide - what do you need?](https://docs.google.com/document/d/1uWGDOkeT9J4acD7rPge468Tme0OotynldsXqtpuGTD8)

We try to prepare a contributor guide for all of you https://docs.google.com/document/d/1uWGDOkeT9J4acD7rPge468Tme0OotynldsXqtpuGTD8/edit?usp=sharing 
Please have a look and comment (what is missing, what is not clear, what you want us to add). We create it for you so all sort of comments are super welcome.

As a result of further discussion and topics brought later by @lifewingmate , we opened this document for people so they can comment event without signing in into google, without even a need to join https://groups.google.com/forum/#!forum/asyncapi-users

> New important features in Generator

This week we release important features:

1. New parameter in templates config - `generator`. It is used to indicate that a given template is compatible only with a specific version of the generator -> https://github.com/asyncapi/generator/pull/309
1. New parameter in templates config - `filters`. This is a breaking change. The way we register filters changes. Now in templates, you can expose your filters as normal functions that do not need Nunjucks environment in the input. This makes testing much easier. We also provide new library of reusable filters, so you do not DRY https://github.com/asyncapi/generator-filters/pull/1. Information on how to migrate in your templates (as the migration of official templates we will handle) will be added to description of this PR https://github.com/asyncapi/generator/pull/298

> Increase adoption activities (topic brought by @lifewingmate )

- Republishing the same content under different domains is completely fine. So if you have a content written in one blog, around AsyncAPI, feel free to share it in AsyncAPI blog, just indicate in the content where the original text was published

- If we get specific signals from the community that our content, our communication channels are not reachable by some parts of communities, just let us know about it, present the case and suggest the tooling that we can use to reach more audiences. The tools and channels that we use at the moment are the most standard we could find and most widely adopted, but we can always adapt.

- Emmelyn will help out to reach local branches of Women Who Code to get the whole community aware of the AsyncAPI initiative as going only through the center is not enough 

> AsyncAPI and Event Modeling (topic brought by Dan Weese )

Dan Weese will create a document describing what he wants to achieve with AsyncAPI document in the Event Modeling process and the need to describe flows in the architecture.

> Model generation vs Generator 1.0 scope (topic brought by @jonaslagoni )

In theory, adding model generation for code generation should not be a breaking change an, therefore, in theory, it is not a must-have for 1.0.0 release of the generator Nevertheless we need to look closer into the topic before 1.0 to be sure. For sure https://github.com/quicktype/quicktype is candidate number one to try out.

## Recording

https://www.youtube.com/watch?v=ro9igMiYIgE

**Comment by Paul-T-AU** [comment]
Have you considered varying the time of the meeting? at least from time to time, as I know a global good time is in possible. CET 6pm is currently 3AM (but more than just me) thats generally the whole of APAC who can't attend.

**Comment by derberg** [comment]
@Paul-T-AU Hey, you mean like 8AM UTC? You're the first one asking for it, which is awesome you did. Added topic to agenda ;)

**Comment by Paul-T-AU** [comment]
@derberg 8AM UTC is perfect ;) but anytime before 11:00 AM UTC or after 20:00 also works too.
