### ISSUE TITLE
AsyncAPI open meeting, Tuesday May 12 2020 8AM UTC

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi#378]
This is the meeting for the AsyncAPI Special Interest Group (SIG). You're invited to [join us](https://zoom.us/j/165106914) and ask questions. 

**WE CHANGED MEETING TIME**
We still meet on alternate Tuesdays, but to make us more friendly to APAC, we change the time of the next meeting to [8AM UTC](https://everytimezone.com/s/9c9d6256). How does it work?
- One meeting a month is at 8AM UTC and one meeting a month is at 4PM UTC
- Join [this](https://groups.google.com/forum/#!forum/asyncapi-users) mailing list to get an always-up-to-date invite to the meeting in your calendar. 

Recordings from the previous meetings are available in [this](https://www.youtube.com/watch?v=S8gvf0XjO10&list=PLbi1gRlP7pijUwZJErzyYf_Rc-PWu4lXS) playlist on YouTube.

If you want to make proposals for the specification and/or the tooling, please reach out in our [Slack workspace](https://www.asyncapi.com/slack-invite) or just leave a comment below.

## Attendees

> Join us if you want to know more about AsyncAPI! The meeting is open to the public.

## Agenda

>Don't wait for the meeting to discuss topics that already have issues. Feel free to comment on them earlier.

1. Q&A
1. Generator disableHooks flag
1. [AsyncAPI React](https://github.com/asyncapi/asyncapi-react) code ownership
1. Deat Letter Queue support in spec
1. Q&A

## Meeting Notes

> Generator disableHooks flag

We discussed a need of having a new flag to disable a single hook function and if disabling of the entire set of hooks (of a given hook type) makes sense.

Follow up issue for implementation -> https://github.com/asyncapi/generator/issues/333

> [AsyncAPI React](https://github.com/asyncapi/asyncapi-react) code ownership

@michal-hudy from Kyma join the call. We discussed that the component that was initially donated by Kyma is no longer only Kyma team supervision but will be steered forward like all other projects under asyncapi organization. Kyma is not abandoning the project and @magicmatatjahu (core contributor of the component) is still there to help with PR reviews.

> Deat Letter Queue support in spec

@Paul-T-AU brought a topic of supporting Dead Letter Queue in the specification. This is a tricky topic as it is not clear if this should be a part of the spec in bindings or not. A suggested approach is to try to have it in spec extension to safely experiment with the best place for such information and then think what's next.

Best would be also to have an issue in this repo so others can see the topic and voice their opinion in the discussion as most of the discussion about it happens on Slack where not everyone follows.

## Recording

https://www.youtube.com/watch?v=A7l1FcK8BHs

**Comment by derberg** [comment]
@all-contributors please add @WaleedAshraf for talk, tool, eventOrganizing
@all-contributors please add @fmvilas for eventOrganizing
@all-contributors please add @evamorcillo for eventOrganizing
@all-contributors please add @derberg for eventOrganizing
@all-contributors please add @MikeRalphson for eventOrganizing
@all-contributors please add @jonaslagoni for eventOrganizing
@all-contributors please add @jerzyn for talk, eventOrganizing

**Comment by derberg** [comment]
@all-contributors please add @WaleedAshraf for talk, tool, eventOrganizing

**Comment by derberg** [comment]
@all-contributors please add @fmvilas for eventOrganizing

**Comment by derberg** [comment]
@all-contributors please add @fmvilas @evamorcillo @derberg @MikeRalphson @jonaslagoni for eventOrganizing

**Comment by michal-hudy** [comment]
One topic: https://github.com/asyncapi/asyncapi-react code ownership 😄

**Comment by derberg** [comment]
@michal-hudy Added!

**Comment by Paul-T-AU** [comment]
A topic I would like to propose, has thought been given to adding Dead Letter Queue definitions? For FIFO use cases it can be beneficial in the consumer having visibility of failed events.
