### ISSUE TITLE
AsyncAPI open meeting, Tuesday May 26 2020 4PM UTC 

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi#384]
This is the meeting for the AsyncAPI Special Interest Group (SIG). You're invited to [join us](https://zoom.us/j/165106914) and ask questions. **The meeting takes place on alternate Tuesdays**. Recordings from the previous meetings are available in [this](https://www.youtube.com/watch?v=S8gvf0XjO10&list=PLbi1gRlP7pijUwZJErzyYf_Rc-PWu4lXS) playlist on YouTube.

**This time we meet at [4PM UTC](https://everytimezone.com/s/b5fb46c3)**

If you want to make proposals for the specification and/or the tooling, please reach out in our [Slack workspace](https://www.asyncapi.com/slack-invite) or just leave a comment below.

Join [this](https://groups.google.com/forum/#!forum/asyncapi-users) mailing list to get an always-up-to-date invite to the meeting in your calendar. 

## Attendees

> Join us if you want to know more about AsyncAPI! The meeting is open to the public.

## Agenda

>Don't wait for the meeting to discuss topics that already have issues. Feel free to comment on them earlier.

1. Q&A
1. Generator 1.0 release. Release strategy agreement.
    Proposal: Create 1.0.0-RC and try it as a lib in the GitHub Action and AsyncAPI Hub. Community to test CLI as much as possible
1. How you feel about how our slack workspace is organized?
1. Microcks.io demo and discussion
1. Q&A

## Notes

> Generator 1.0 release. Release strategy agreement.

We go with 1.0.0-rc1 and we will announce it on all the channels to get the community involved in testing.

> How you feel about how our slack workspace is organized?

Best would be to prepare a kind of survey that will be sent out to all slack members to get clarification if changes are needed or not

> Microcks.io demo and discussion

That was a great demo about testing event-driven architectures at scale. Folks will add support for AsyncAPI in next release, for Kafka at the moment.

## Recording

https://www.youtube.com/watch?v=5-kiebb0j90

**Comment by lbroudoux** [comment]
Hi AsyncApi community !

If possible, I'd like to introduce you Microcks.io : a tool for mocking and testing APIs that will support AsyncAPI 2.0 specification in next release. I have posted a teaser video yesterday: https://www.youtube.com/watch?v=uZaWAekvUz4

We'd really like to have your feedback on that one! I'll be able to replay the demo and have Q&A if time slot allows it.

**Comment by derberg** [comment]
@lbroudoux added to agenda, looking forward

I'll send meeting invite update to https://groups.google.com/forum/#!forum/asyncapi-users so people know what is on the agenda
