### ISSUE TITLE
Spec definition revision

### ISSUE THREAD

**Issue by BlockLucas** [asyncapi/asyncapi#397]
Hi!

We have seen some inconsistencies in the spec that needs clearing out and some updates to the spec that are not backwards compatible or add things and are updated in the same 2.0.0 version.

1. $ref not defined in every level it may be defined. Check OAS specs for instance, it’s strictly defined where $ref field can be used and where it can’t, it’s not a free form inclusion to the AST. For example, there can’t be a $ref in an info object. A place where this is completely misleading is in the use of traits. The operation has an array of trait objects, but the field $ref is not there, so it can’t be referenced. It also states that the objects can be present in that array, which makes no sense the traits facet should only have refs. What would be the point of having an inline trait? Not having refs strictly defined (as OAS has) is confusing for the user.
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#file-structure

2. Default media type in root schema is missing.
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#asyncapi-object
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#default-content-type

3. ABNF for runtime expressions has an error: header-reference and payload-reference have a dot before the hashtag and the fragment, which makes no sense. 
header-reference = "header." ["#" fragment]
payload-reference = "payload." ["#" fragment]
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#runtime-expression

4. Operation object facet tags has an array of Tag Object and operation trait object facet tags has an instance of Tags Object. They must be the same type.
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#operation-trait-object
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#operation-object

5. Message object examples facet has a wrong type. It’s an array of Maps, it should be only a Map. Message trait objects have the same problem.
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#message-object
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#message-trait-object

6. Bindings: "message" of MQTT server binding is defined in the example but not in schema table
https://github.com/asyncapi/bindings/blob/master/mqtt/README.md#server-binding-object
https://github.com/asyncapi/bindings/blob/master/mqtt/README.md#example

7. Spec updated in the same branch: Bindings used to be a free-form map, this is no longer the case, what about unknown protocols? We are supporting known protocols and unknown protocols as free form nodes, now unknown protocols are no longer supported.

8. Spec updated in the same branch: Mercure binding is new and was unsupported.

**Comment by fmvilas** [comment]
Hey @BlockLucas! Thanks for your patience. These are very good points that need to be solved. Would you mind opening an issue for each of them so we can address/discuss each one individually?

**Comment by fmvilas** [comment]
Since some of you are asking privately about the process, here's the contribution process: https://github.com/asyncapi/.github/blob/master/CONTRIBUTING.md. We don't need to discuss everything a lot, some of these issues are clearly bugs in the docs and just need some minimal discussion on how to fix it and the pull request fixing it after the issue is good to go.

**Comment by BlockLucas** [comment]
Thanks!, ive created a bug for each point, if you want, lets close this one & keep the conversation going on the sub-issues.

Regards!

**Comment by fmvilas** [comment]
Awesome! Thanks, @BlockLucas 🙏
