### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by MikeRalphson** [asyncapi/asyncapi#4]
> The AsyncAPI Specification is licensed under The Apache License, Version 2.0.

This is great as OAS is also under Apache 2.0, but is it correct that `package.json` states MIT?

**Comment by bpedro** [comment]
Thanks for the feedback, @MikeRalphson.

Here's an update that addresses the issue you found: https://github.com/asyncapi/asyncapi/pull/5

**Comment by MikeRalphson** [comment]
LGTM.
