### ISSUE TITLE
AWS SNS support would be great

### ISSUE THREAD

**Issue by SkippyZA** [asyncapi/asyncapi#40]
Currently covering our topics with this and it would be great to have some official SNS support

edit: incorrectly used `sqs` instead of `sns`

**Comment by fmvilas** [comment]
Hey! Thanks for pointing out. As per documentation AWS SNS is not a protocol but a product supporting many protocols:

```
The protocol you want to use. Supported protocols include:

* http -- delivery of JSON-encoded message via HTTP POST
* https -- delivery of JSON-encoded message via HTTPS POST
* email -- delivery of message via SMTP
* email-json -- delivery of JSON-encoded message via SMTP
* sms -- delivery of message via SMS
* sqs -- delivery of JSON-encoded message to an Amazon SQS queue
* application -- delivery of JSON-encoded message to an EndpointArn for a mobile app and device.
* lambda -- delivery of JSON-encoded message to an AWS Lambda function.
```

http://docs.aws.amazon.com/sns/latest/api/API_Subscribe.html

So in which protocol would you be interested?

**Comment by fmvilas** [comment]
I'm closing the issue as it's already a week old without response. Feel free keep commenting.

**Comment by SkippyZA** [comment]
Somehow my notification for this went missing.

So while SNS does support multiple methods to subscribe to it, that I see is some 'implementation' logic. At the very least, the ability to specify that the API is SNS. Perhaps have the ability so specify the account id, region etc would be great. This could perhaps be used to build up the ARN?

With regards to consuming a message, I believe the event data will be the same regardless of which approach you use to subscribe to it. 

I have also tried the approach of setting the base topic to represent the ARN, but when it joins the actual stream, it uses a `.` and not `:` needed for the arn resulting in: `arn:aws:sns:{region}:{accountId}.TopicName`

**Comment by fmvilas** [comment]
I think your best friend here is [Specification Extensions](https://github.com/asyncapi/asyncapi#specificationExtensions). 
This way you can specify whatever custom properties you might need:

```yaml
x-sns-region: 'us-east-1'
x-sns-accountId: 'your-account-id-here'
```

The only thing you'd have to do is to tweak documentation generator and/or code generator to use those values.
