### ISSUE TITLE
AsyncAPI open meeting, Tuesday Jul 21 2020 4PM UTC 

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi#404]
This is the meeting for the AsyncAPI Special Interest Group (SIG). You're invited to [join us](https://zoom.us/j/165106914) and ask questions. **The meeting takes place on alternate Tuesdays**. Recordings from the previous meetings are available in [this](https://www.youtube.com/watch?v=U6h7LwdEr0w&list=PLbi1gRlP7pijUwZJErzyYf_Rc-PWu4lXS) playlist on YouTube.

**This time we meet at [4PM UTC](https://everytimezone.com/s/dc9143e6)**

If you want to make proposals for the specification and/or the tooling, please reach out in our [Slack workspace](https://www.asyncapi.com/slack-invite) or just leave a comment below.

Join [this](https://groups.google.com/forum/#!forum/asyncapi-users) mailing list to get an always-up-to-date invite to the meeting in your calendar. 

## Attendees

> Join us if you want to know more about AsyncAPI! The meeting is open to the public.

## Agenda

>Don't wait for the meeting to discuss topics that already have issues. Feel free to comment on them earlier.

1. Q&A
1. Request/Reply pattern in bindings (NATS related) — @jonaslagoni 
1. Q&A

## Notes

- We discussed request/reply features for #NATS
- We're figuring out how to solve the publish/subscribe concerns

## Recording 

https://www.youtube.com/watch?v=U6h7LwdEr0w

**Comment by jonaslagoni** [comment]
I would like to discuss/ask a question regarding temporary view for request/reply pattern in bindings if possible. This is related to the NATS Typescript template.

**Comment by fmvilas** [comment]
@jonaslagoni Added to the agenda 👍
