### ISSUE TITLE
Default media type in root schema is missing.

### ISSUE THREAD

**Issue by BlockLucas** [asyncapi/asyncapi#407]
Issue part of #397

https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#asyncapi-object
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#default-content-type

**Comment by derberg** [comment]
oh, this is quite a gap, surprised that so far nobody else noticed that 😄 good 👁️ 
would you mind filling in a PR for that?

**Comment by BlockLucas** [comment]
Closing as has been resolved & merged
