### ISSUE TITLE
ABNF for runtime expressions has an error

### ISSUE THREAD

**Issue by BlockLucas** [asyncapi/asyncapi#408]
Issue part of #397

header-reference and payload-reference have a dot before the hashtag and the fragment, which makes no sense.
header-reference = "header." ["#" fragment]
payload-reference = "payload." ["#" fragment]
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#runtime-expression

**Comment by derberg** [comment]
Hey, would ❤️ to see what is the correct version and the reasoning behind it

**Comment by gutee** [comment]
Hi @derberg, I can see runtime expressions here have been taken from [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#runtime-expressions). But a hybrid was left of some of the expressions there, just imagine the use of this where you want to express a fragment of a header: it would be something like `Content-Type.#some-fragment`. You can immediately see the dot doesn't have to be there, as the common notation to navigate through fragments is the hashTag, the dot just doesn't make sense in the flow of the expression. It should just be:

```
header-reference = "header" ["#" fragment]
payload-reference = "payload" ["#" fragment]
```

**Comment by fmvilas** [comment]
Yeah, this is definitely wrong. This dot must not be there.
