### ISSUE TITLE
Operation object facet tags has an array of Tag Object and operation trait object facet tags has an instance of Tags Object.

### ISSUE THREAD

**Issue by BlockLucas** [asyncapi/asyncapi#409]
Issue part of #397

They must be the same type.
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#operation-trait-object
https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#operation-object

**Comment by derberg** [comment]
Hey. Good 👁️ . Would you mind filling in a PR to fix the description of Operation Trait? Schema is [fine](https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/schema.json#L826) so just the markdown fine has to be updated
