### ISSUE TITLE
Spec updated in the same branch: Mercure binding is new and was unsupported.

### ISSUE THREAD

**Issue by BlockLucas** [asyncapi/asyncapi#413]
Issue part of #397

**Comment by derberg** [comment]
Hi @BlockLucas can you elaborate a bit more about the issue. I know Mercure support was added to the spec but to master only. It was not updated on the website

**Comment by fmvilas** [comment]
Updating the spec in the same branch is not my favorite thing either. It's very confusing. However, it's still a correct and valid approach. If you want to know which is the stable version, you should browse files on the `2.0.0` tag: https://github.com/asyncapi/asyncapi/tree/2.0.0.

Mercure support will be added in the next version of the spec, most likely on 2.1.0. Sorry for the confusion with master == stable. This needs to be changed or clarified.
