### ISSUE TITLE
AsyncAPI open meeting, Tuesday Aug 18 2020 4PM UTC

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi#425]
This is the meeting for the AsyncAPI Special Interest Group (SIG). You're invited to [join us](https://zoom.us/j/165106914) and ask questions. **The meeting takes place on alternate Tuesdays**. Recordings from the previous meetings are available in [this](https://www.youtube.com/watch?v=S8gvf0XjO10&list=PLbi1gRlP7pijUwZJErzyYf_Rc-PWu4lXS) playlist on YouTube.

**This time we meet at [4PM UTC](https://everytimezone.com/s/48cdc0da)**

If you want to make proposals for the specification and/or the tooling, please reach out in our [Slack workspace](https://www.asyncapi.com/slack-invite) or just leave a comment below.

Join [this](https://groups.google.com/forum/#!forum/asyncapi-users) mailing list to get an always-up-to-date invite to the meeting in your calendar. 

## Attendees

> Join us if you want to know more about AsyncAPI! The meeting is open to the public.

## Agenda

>Don't wait for the meeting to discuss topics that already have issues. Feel free to comment on them earlier.

1. Q&A
1. _(Leave a comment below to add your item to the agenda)_
1. Generating the HTML template from the React component to remove duplicates ([issue](https://github.com/asyncapi/html-template/issues/51)) (@fmvilas ) <- moved to next meeting when Fran is back
1. Generator and parser releases status (@derberg)
1. Error handling in parser https://github.com/asyncapi/parser-js/issues/119 (@derberg)
    - custom errors
    - what about warnings
1. CI Workflow improvements https://github.com/asyncapi/asyncapi/issues/423 (@derberg)
    - forks support!
    - merging through labels
1. Q&A

## Notes

Notes for the issues mentioned above are added directly to the issues.

We also talked about [this](https://youtu.be/U3IbRSVK2vk) installation issue, that it is happening not only for the generator used from sources, but also when used as npm global installation. @derberg will investigate further.

We also talked about the NATS projects, and to be more specific the future of JS client and also the best way to use C# client in the code generator that @jonaslagoni works on. Thank you @aricart for joining the call and all the support during it. I'd love to pay back, in case you are interested more in our GitHub Actions pipeline and how we fully automated releases with conventional commits, have a look at my blog post about it https://www.asyncapi.com/blog/automated-releases/ and feel free to ping me on AsyncAPI or NATS slack workspaces when you have some questions.

## Recording 

https://youtu.be/U3IbRSVK2vk

**Comment by aricart** [comment]
@derberg it was a pleasure to participate!

**Comment by matthewadams** [comment]
@derberg I'm a noob to this project. What are the "NATS projects"?

**Comment by jonaslagoni** [comment]
@matthewadams he is referring to the [open source messaging system NATS](https://nats.io/) which @aricart is apart of, where in the meeting we talked about the status of their clients and some questions I had in regards to wrapping it in templates for [Node js / Typescript](https://github.com/asyncapi/ts-nats-template) and [.NET](https://github.com/asyncapi/dotnet-nats-template) 😄
