### ISSUE TITLE
How to distribute definition over different files.

### ISSUE THREAD

**Issue by anandrachit** [asyncapi/asyncapi#429]
Hi, 

First of all, thanks for the great work. This is more of a question really, rather than a bug. 

In my project, I am using Swagger 2.0, on a node express server for the REST API definitions. For the definition of the APIs, I write comments on each API with the `@swagger` decorator for Swagger to pick up the documentation. For example:
```
/**
* @swagger
* /user/register:
*   post:
*     description: Register a new user
...
...
*/
```

I also have a `common` definition in a `routes` file, where I define all the reusables. 

Swagger, collects all these documentations distributed over various files, and creates a single documentation for all the APIs in the application. 

I was wondering if we had something similar in AsyncAPI and if yes, how do I achieve that. 

What I need to do is, rather than creating a single yaml/json file for all the messages in the application, I want to create the AsyncAPI definition for each message in its own file, very much like its done in Swagger. 

Would really appreciate your response on this.

Thanks, 
Rachit

**Comment by derberg** [comment]
atm there is nothing for the code-first approach for node.js that I'm aware of. At AsyncAPI we prefer api-first. Here you have a list of all the community tools around code-first https://www.asyncapi.com/docs/tooling/#code-first

**Comment by derberg** [comment]
the only thing you can do without such tooling is to keep message payload files in separate location next to the file with the code, and then `$ref` it in a main file. So list of channels in main file but message definition `$ref`ed from external file.

**Comment by anandrachit** [comment]
@derberg : Thanks so much for the response. Since there is no code-first approach for node.js, the best approach for me is to place all the yaml in one single file and generate a documentation from there.

Appreciate your response and the great work with Async API!!!

**Comment by derberg** [comment]
@anandrachit thanks for good words. In case you have more questions in the future keep in mind we have a slack workspace https://www.asyncapi.com/slack-invite/ so feel invited ;)

**Comment by matthewadams** [comment]
I just discovered AsyncAPI this morning.  I prefer code-first, but only because most of the code generators out there suck, IMHO.  They'll prolly _never_ generate code that is exactly what people want.  I was thinking about a JavaScript decorator-based approach here, where your decorator implementations generate a spec based on the reflective information given to the decorator.  Might be a nice way to do things.  While decorators are still pretty experimental, I think it could work pretty effectively.

**Comment by derberg** [comment]
@matthewadams we would love to hear more about those bad generators. We have a generator https://github.com/asyncapi/generator/ that has a purpose to change the perception of generators. We are opened to feedback. Unless you mean you do not like specific templates, so any feedback about https://github.com/asyncapi/nodejs-template would be welcome
