### ISSUE TITLE
Remove not needed try/catch from the test

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi#440]
*Context*

SonarCloud says that [this](https://github.com/asyncapi/asyncapi/blob/master/test/index.js#L15-L39) try/catch is a code smell because we are anyway not doing anything special in the `catch` clause. 

*Description*

Instead of adding there `console.error` it is better to remove the try/catch statement as the error will bubble up anyway to the `runForVersion` function where error is handled much better.﻿

**Comment by HashTalmiz** [comment]
Hey. This seems to be pretty simple, can I take this up?
