### ISSUE TITLE
AsyncAPI open meeting, Tuesday Oct 27 2020 8AM UTC

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi#455]
This is the meeting for the AsyncAPI Special Interest Group (SIG). You're invited to [join us](https://zoom.us/j/165106914) and ask questions. **The meeting takes place on alternate Tuesdays**. Recordings from the previous meetings are available in [this](https://www.youtube.com/watch?v=S8gvf0XjO10&list=PLbi1gRlP7pijUwZJErzyYf_Rc-PWu4lXS) playlist on YouTube.

**This time we meet at [8AM UTC](https://everytimezone.com/s/577ca99f)**

If you want to make proposals for the specification and/or the tooling, please reach out in our [Slack workspace](https://www.asyncapi.com/slack-invite) or just leave a comment below.

Join [this](https://groups.google.com/forum/#!forum/asyncapi-users) mailing list to get an always-up-to-date invite to the meeting in your calendar. 

## Attendees

> Join us if you want to know more about AsyncAPI! The meeting is open to the public.

## Agenda

>Don't wait for the meeting to discuss topics that already have issues. Feel free to comment on them earlier.

1. Q&A
1. Microcks update on AsyncAPI support by @lbroudoux
1. Hacktoberfest summary by @derberg 
1. Q&A

## Notes

Lukasz could not join and Laurent did a live demo of Microcks.

## Recording 

https://www.youtube.com/watch?v=pmRA4M-TWuE

**Comment by lbroudoux** [comment]
Hi all!

I'd like to propose a demo and discussion about next Microcks.io release that will embed automated testing of asynchronous API on Kafka using AsyncAPI schema validation. 

Tell me if interested! 

Thanks,

Ps: is the meeting time 8am UTC? Because it still appears at 6pm UTC in my agenda.
