### ISSUE TITLE
Do you have any UI libraries I can use to show asyncAPI UI on my internal site like swagger UI?

### ISSUE THREAD

**Issue by rols2015** [asyncapi/asyncapi#478]

**Comment by derberg** [comment]
Hey, we have a react component and also provide it as a web component (in case you have some non-SPA UI or Angular)

https://github.com/asyncapi/asyncapi-react/

**Comment by rols2015** [comment]
closing, since I got an answer in slack channel.

**Comment by johnthagen** [comment]
@rols2015 Would you be able to provide the answer you got in slack on this issue so others can see it? Or is it the same answer as @derberg provided above?

**Comment by magicmatatjahu** [comment]
@johnthagen You can use `standalone` bundle (similar to the Swagger UI), or use the `web-component`. Here is a docs:
- standalone bundle https://github.com/asyncapi/asyncapi-react/blob/next/docs/usage/standalone-bundle.md
- web-component https://github.com/asyncapi/asyncapi-react/blob/next/docs/usage/web-component.md
