### ISSUE TITLE
AsyncAPI open meeting, Tuesday Feb 2 2021 4PM UTC

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi#480]
This is the meeting for the AsyncAPI Special Interest Group (SIG). You're invited to [join us](https://zoom.us/j/165106914) and ask questions. **The meeting takes place on alternate Tuesdays**. Recordings from the previous meetings are available in [this](https://www.youtube.com/watch?v=S8gvf0XjO10&list=PLbi1gRlP7pijUwZJErzyYf_Rc-PWu4lXS) playlist on YouTube.

**This time we meet at [4PM UTC](https://everytimezone.com/s/35133803)**

If you want to make proposals for the specification and/or the tooling, please reach out in our [Slack workspace](https://www.asyncapi.com/slack-invite) or just leave a comment below.

Join [this](https://groups.google.com/forum/#!forum/asyncapi-users) mailing list to get an always-up-to-date invite to the meeting in your calendar. 

## Attendees

> Join us if you want to know more about AsyncAPI! The meeting is open to the public.

## Agenda

>Don't wait for the meeting to discuss topics that already have issues. Feel free to comment on them earlier.

1. Q&A
1. _(Leave a comment below to add your item to the agenda)_
1. discuss the status of #329 and some other bindings RFE (asyncapi/bindings#41, asyncapi/bindings#40) and how to move forward on these -> @lbroudoux
1. updates on CI setup -> @derberg 
1. Q&A

## Notes

> discuss the status of #329 and some other bindings RFE (asyncapi/bindings#41, asyncapi/bindings#40) and how to move forward on these

  - Fran and Lukasz are now fully focused on getting AsyncAPI into a foundation and picking the right open governance model where the project is governed by people that are active and contribute and not "buy-in" the vot. There are advanced discussion switch Linux Foundation
  - Because of the above we do not want to make any decisions about making changes in the spec because now the majority of people working on asyncapi actively are part of Postman and this could cause the community to not feel right about it
  - This doesn't mean work should be freezed. Push your issues forward, open PRs. Basically, prepare everything that is needed for the governance board to vote on.
  - We also need to work on a clear release process for future spec releases. We need help to kick off work around this topic. Please open a new issue and kick-off discussion. Some ideas are already in this PR https://github.com/asyncapi/asyncapi/pull/468

> updates on CI setup 
  - conventional commits are now mandatory everywhere, we lint PR titles and block merge if https://www.conventionalcommits.org/en/v1.0.0/ is not used
  - we do testing, and run all basic scripts on macs, linux and windows
  - we will automatically send a tweet about any major/minor release from any repo + send info about all releases to #github-releases slack channel
  - traffic on all new PRs and issues can be monitored in #github-new-issues-prs slack channel
  - cool 2 issues to contribute to doing CI/CD config -> https://github.com/asyncapi/.github/issues

## Recording 

https://youtu.be/vAcTtr__CwU

**Comment by lbroudoux** [comment]
Hi @derberg !

I'd like to discuss the status of https://github.com/asyncapi/asyncapi/issues/329 and some other bindings RFE (https://github.com/asyncapi/bindings/issues/41, https://github.com/asyncapi/bindings/issues/40) and how to move forward on these.

Is it a good topic candidate?

Cheers,

**Comment by derberg** [comment]
@lbroudoux definitely, added
