### ISSUE TITLE
Multiple paramenters in topic

### ISSUE THREAD

**Issue by riccardo1991** [asyncapi/asyncapi#49]
Hello, I encountered a possible bug if I try to put multiple parameters/variables in a single topic. 
 
For example creating a topic as `event.{streetlightId}.lighting.{banana}.measured` 

I get `.event.:streetlightId}.lighting.{banana.measured` on the rendered page.

I suppose multiple params are not supported yet, right?

**Comment by fmvilas** [comment]
Hey @riccardo1991! I guess you mean the AsyncAPI docgen, right? This repo doesn't contain any documentation renderer.

**Comment by riccardo1991** [comment]
I mean the online editor http://editor.asyncapi.org/

**Comment by fmvilas** [comment]
Oh ok, so it's the docgen. Will open the issue there. Thanks for reporting.
