### ISSUE TITLE
[BUG] Server Variable Object missing in Schema Index

### ISSUE THREAD

**Issue by char0n** [asyncapi/asyncapi#499]
I've noticed that Server Variable Object is missing in index of main Schema definitions: https://github.com/asyncapi/asyncapi/blob/master/versions/2.0.0/asyncapi.md#schema

**Comment by char0n** [comment]
The same applies for:
- Server Object

**Comment by derberg** [comment]
@char0n hey, sorry but could you specify what you mean? `Servers` is one of main definitions, then `Server` is one of `Servers` and `Server Variable` is part of `Server`

**Comment by char0n** [comment]
Ah ok I get it, so only top level objects are within Schema index. Would be nice to have all specification objects included in Schema  as for example OpenApi specification does.

![image](https://user-images.githubusercontent.com/193286/107936272-bcdd8d80-6f82-11eb-905d-bdfeb55395ec.png)

It's easier to work with the spec that way.

**Comment by derberg** [comment]
you mean something more than just this table of contents?

![Screenshot 2021-02-15 at 12 28 02](https://user-images.githubusercontent.com/6995927/107940924-44c69600-6f89-11eb-885f-644848ddb3fb.png)

**Comment by char0n** [comment]
Yep, sorry for being unclear. It would help tremendously navigating the specification if all Objects from the specification would be mentioned in this TOC (like Server Object, Security Requirement Object) not only the top level objects.

**Comment by derberg** [comment]
@char0n no worries, thanks for clearing this out. Makes sense what you write. Would you mind opening a PR for this?

**Comment by char0n** [comment]
> Would you mind opening a PR for this?

Sure I'll open it directly against current master. Thanks

**Comment by char0n** [comment]
Attaching the [PR](https://github.com/asyncapi/asyncapi/pull/500). Along with improving TOC I've fixed some naming inconsistencies of using object names, which prevented for searching for them inside document.
