### ISSUE TITLE
AsyncAPI open meeting, Tuesday Mar 2 2021 4PM UTC 

### ISSUE THREAD

**Issue by derberg** [asyncapi/asyncapi#504]
This is the meeting for the AsyncAPI Special Interest Group (SIG). You're invited to [join us](https://zoom.us/j/165106914) and ask questions. **The meeting takes place on alternate Tuesdays**. Recordings from the previous meetings are available in [this](https://www.youtube.com/watch?v=S8gvf0XjO10&list=PLbi1gRlP7pijUwZJErzyYf_Rc-PWu4lXS) playlist on YouTube.

**This time we meet at [4PM UTC](https://everytimezone.com/s/667f7d29)**

If you want to make proposals for the specification and/or the tooling, please reach out in our [Slack workspace](https://www.asyncapi.com/slack-invite) or just leave a comment below.

Join [this](https://groups.google.com/forum/#!forum/asyncapi-users) mailing list to get an always-up-to-date invite to the meeting in your calendar. 

## Attendees

> Join us if you want to know more about AsyncAPI! The meeting is open to the public.

## Agenda

>Don't wait for the meeting to discuss topics that already have issues. Feel free to comment on them earlier.

1. Q&A
1. Update from @dalelane about:
    - Describing schema usage in Kafka 
      - https://github.com/asyncapi/bindings/pull/55 
      - [examples](https://gist.github.com/dalelane/3931c17b14c51fa4a1cf25496237d188)
    - Defining security parameters for Kafka 
      - https://github.com/asyncapi/bindings/pull/56
      - https://github.com/asyncapi/asyncapi/pull/502
1. [Vision of the project](https://deploy-preview-189--asyncapi-website.netlify.app/roadmap) on [PR](https://github.com/asyncapi/website/pull/189) by @fmvilas 
1. Update on governance model by @derberg 
1. Some updates in the templates world from @derberg ([PHP](https://github.com/asyncapi/asyncapi-php-template) and [Go](https://github.com/asyncapi/go-template) templates)
1. Q&A

## Notes

- We got update from Dale on efforts:
  - to provide security schemes in the spec that are relevant for Kafka
  - to add server binding for Kafka
  
  (above, in the agenda you have links to PRs and examples)
- We had a discussion brought by Ian on the idea of bindings on a server in general. The current state is that spec describes the app and should have things that are necessary to identify how to connect to the app. In the case of the server, binding is to keep details about the broker needed for the app to connect, not the configuration details of the server so it can be used for infrastructure setup. This is a state for now, but nothing blocks us from changing it and we can discuss it in the `asyncapi` repo issues
- We also had a discussion brought by Lorna about the security details that should be in the spec. The current approach is that credentials should not be there. Through spec you should know that to connect to a broker you need user name and password, but you should not know what is the user name and password.
- Fran showed an initial preview of the project vision and roadmap. Have a look and share your feedback in the PR https://github.com/asyncapi/website/pull/189
- Lukasz shared that we finished working on the open governance model last week already. We are just waiting on the foundation's feedback and a green light if we can share it already with the community and work with the community and foundation in parallel on fixes in the charter. We will share charter as a PR to asyncapi repo + a blog post with the motivation behind it. The community will have 2 weeks to provide feedback.
- Lukasz shared that we have new template, [PHP](https://github.com/asyncapi/asyncapi-php-template) one, underdevelopment, donated by Emiliano that wants to work on it with the community
- Lukasz shared the work on [Go](https://github.com/asyncapi/go-template)  continues after few months of stale. Jacob cannot continue but we merged his PR and Takumi with Emiliano want to continue with it forward.

## Recording 

https://youtu.be/NITAyTedR5c

**Comment by dalelane** [comment]
If there's interest in giving an update on the progress of these items, I'd be happy to give a quick summary:

- Describing schema usage in Kafka 
    - https://github.com/asyncapi/bindings/pull/55 
- Defining security parameters for Kafka 
    - https://github.com/asyncapi/bindings/pull/56
    - https://github.com/asyncapi/asyncapi/pull/502

**Comment by derberg** [comment]
@dalelane sure thing, this meeting is for the community, so if you only have time to do it then please do. I'll add it to the agenda!
