### ISSUE TITLE
xml object and root schemas

### ISSUE THREAD

**Issue by MikeRalphson** [asyncapi/asyncapi#57]
The xml example/test document uses the [xml object](https://github.com/asyncapi/asyncapi/tree/v2#xmlObject) on a root schema.

https://github.com/asyncapi/asyncapi/blob/70bb40a42a463917a963e544ae4b2395bf40b22e/test/docs/xml.yaml#L29-L32

From the spec.

> This MAY be used only on properties schemas. It has no effect on root schemas. Adds Additional metadata to describe the XML representation format of this property.

It may be worth following the discussion [here](https://github.com/OAI/OpenAPI-Specification/issues/1435) to see how a similar issue gets resolved in the OAS, or simply clarifying the wording in AsyncAPI to allow this.

**Comment by fmvilas** [comment]
You're right. In my opinion, it would make sense to have it there. Let's wait for the OAS guys to see what they say, so we're aligned. Thanks for pointing out!
