### ISSUE TITLE
Guidelines on anyOf

### ISSUE THREAD

**Issue by SensibleWood** [asyncapi/asyncapi#58]
When I attempt to include `anyOf` in Async API editor a schema definition I get the following:

`[
  {
    "code": "OBJECT_ADDITIONAL_PROPERTIES",
    "params": [
      [
        "anyOf"
      ]
    ],
    "message": "Additional properties not allowed: anyOf",
    "path": "#/components/schemas/DirectDebit/allOf/1",
    "schemaId": "http://asyncapi.hitchhq.com/v1/schema.json#",
    "description": "A deterministic version of a JSON Schema object."
  }
]`

However I can't see anywhere in the documentation that says `anyOf` is specifically excluded.

Please can you clarify where anyOf is supported or not? Thanks.

**Comment by fmvilas** [comment]
Hey @SensibleWood! Yes, that's currently not supported by mistake. I'm already fixing it for version 2.0.0, which will be out very soon.

Thanks for pointing out! Will update whenever it gets fixed.

**Comment by SensibleWood** [comment]
Nice one thanks @fmvilas - attempting to use Async API in anger in some projects I'm working on - it's great work

**Comment by fmvilas** [comment]
Thanks @SensibleWood! Really appreciate 😊

**Comment by fmvilas** [comment]
Will be fixed in v1.1.0. Make sure it also covers the problem described at #38.
