### ISSUE TITLE
Question: would newline-delimited JSON be considered a valid "server.scheme"?

### ISSUE THREAD

**Issue by nelz9999** [asyncapi/asyncapi#62]
Dunno if the spec helps: https://tools.ietf.org/html/rfc7464#section-2.2

I'm thinking about how to beef up the documentation/description of an endpoint that delivers information this way... 

The general shape of the endpoint is already described in OpenAPI (Swagger) 2.0, but it doesn't give a good way to describe the several type of JSON objects emitted.

**Comment by fmvilas** [comment]
Hi @nelz9999,

It's very interesting. I never heard about JSON text sequences, thanks for sharing.

Is it something you would use over HTTP, AMQP or another protocol? Or is it the communication protocol itself?

Can you provide an example on how an implementation would look like?

**Comment by nelz9999** [comment]
We use it over HTTP, and stream delivery of the JSON bodies... These connections are kept open for tens of minutes, or longer. (Internally, we call this our "long-poll GET".)

The "raw" content coming across the wire would look sort of like this:
```
{"eventType": 0, "data":"example"}\n
\n
\n
{"eventType":1, "otherStuff": "more example"}\n
\n
\n
```

(The empty lines are what we use as "keepalive" signals.)

**Comment by fmvilas** [comment]
Oh ok, I understand now. I think you'll benefit from AsyncAPI v2 Streaming APIs feature. Check an example here: https://github.com/asyncapi/asyncapi/blob/v2/test/docs/gitter-streaming.yaml.

The server scheme will be HTTP but there will be another section in the spec to document streaming APIs.

**Comment by nelz9999** [comment]
Ahhh okay! Great. I'll keep an eye out for v2!
