### ISSUE TITLE
API License Type: Should this not be an array type of one or more license types?

### ISSUE THREAD

**Issue by marchon** [asyncapi/asyncapi#63]
https://github.com/asyncapi/asyncapi/blob/81e43fa61c34a3ed01aef75c6269ea590efc3a04/schema/asyncapi.json#L142

**Comment by fmvilas** [comment]
This information is exactly the same as in OpenAPI. However, I'm not sure if this has changed.

The goal is to keep as much OpenAPI compatibility as possible.
