### ISSUE TITLE
The transfer protocols listed does not appear to be complete to me

### ISSUE THREAD

**Issue by marchon** [asyncapi/asyncapi#64]
There are a variety of message brokers that implement an even larger variety of messaging protocols.  

The transfer protocols listed does not appear to be complete to me.  At first it occurred to me that it was missing 0mq, nanomsg and some others so I searched further. 

A quick set of internet searches returned: SMTP, HTTP, JMS, AMQP, STOMP, XMPP, MQTT, and OpenWire 

I would be interested in trying to complete this list if there is interest. 

There are a variety of message brokers that implement an even larger variety of messaging protocols.  

> Kafka is well adopted today within the Apache Software Foundation ecosystem of products and is particularly useful in event-driven architecture. 

> RabbitMQ is designed as a general purpose message broker, employing several variations of point to point, request/reply and pub-sub communication styles patterns.  It uses a smart broker / dumb consumer model, focused on consistent delivery of messages to consumers that consume at a roughly similar pace as the broker keeps track of consumer state.

          "enum": [
            "kafka",
            "kafka-secure",
            "amqp",
            "amqps",
            "mqtt",
            "mqtts",
            "secure-mqtt",
            "ws",
            "wss",
            "stomp",
            "stomps"
          ]

https://github.com/asyncapi/asyncapi/blob/81e43fa61c34a3ed01aef75c6269ea590efc3a04/schema/asyncapi.json#L188

**Comment by fmvilas** [comment]
Agree. The reason not all the protocols are there is because we wanted to follow an iterative approach, making sure AsyncAPI fits in each of the listed protocols first, and then adding it.

One way to improve it could be to demonstrate that AsyncAPI could be used with protocol X and then adding it. I'm sorry but I really have no time to check on all of them but feel free to investigate and make PRs.
