### ISSUE TITLE
Version 1.1

### ISSUE THREAD

**Issue by MikeRalphson** [asyncapi/asyncapi#69]
Is this a new version of the spec, or a 1.1 revision of the 1.0.0 spec?

I.e. is a topic parameter valid in an asyncapi document which uses `asyncapi: 1.0.0` ?

https://github.com/asyncapi/asyncapi/blob/3a45dad21f4536c1a87c2ca0aea1e651e95456de/test/docs/sample.yml#L1

**Comment by fmvilas** [comment]
Good catch. It's a new version. Parameters should not be available in 1.0.0. Fixing it. Thanks!
