### ISSUE TITLE
Allow re-usable `parameters` reffed to `components`

### ISSUE THREAD

**Issue by MikeRalphson** [asyncapi/asyncapi#71]
See https://github.com/asyncapi/asyncapi/blob/0684308ae117a2cf2b710613989aa65ea261a1f6/test/docs/sample.yml#L34-L45

where the necessary `streetlightId` parameter is only defined for one topic, but it would be useful to be able to `$ref` a re-usable *Parameter Object*

If approved will target a PR at ... v1.2.0 ?

**Comment by fmvilas** [comment]
Yeah, I realized about that when writing the sample file. Adding it to components would be great. Go for it 👍
