### ISSUE TITLE
Correlation Ids

### ISSUE THREAD

**Issue by andreimarculescu** [asyncapi/asyncapi#78]
Would it be a good idea for AsyncAPI to support built-in correlation ids to enable distributed tracing ? 

I would see this as a (optional?) parameter correlationId under #/definitions/operation. The value of this parameter must be the name of one of properties defined in the message schema for the operation.

Automated tracing tools could be implemented with no knowledge of the internal implementation behind the APIs (these tools can listen to publish topics and aggregate on the values of correlationId). Clients of subscribe topics would be aware of the correlation semantics of a particular property in the message they must send to the subscriber of the topic.

**Comment by fmvilas** [comment]
I think this is a very interesting feature. Not sure this should be part of the spec though. Why not using specification extension, e.g., `x-correlation-id`?

**Comment by andreimarculescu** [comment]
I suggested it to be part of the spec because correlation between inputs and outputs is a fundamental difficulty of asynchronous systems, whereas for synchronous systems inputs / outputs are naturally linked. I don't mind implementing it as a vendor extension, but in the world of heterogeneous async systems (microservices), everyone should implement the same extension, which seems to me harder to achieve.

**Comment by fmvilas** [comment]
Fair point.

**Comment by fmvilas** [comment]
I'm marking this issue to be released on next minor version, v1.3.0.

**Comment by fmvilas** [comment]
Thanks for the great suggestion @andreimarculescu.

**Comment by SensibleWood** [comment]
I'm going to pick this up my next issue. BRB...

**Comment by SensibleWood** [comment]
# Proposal

Proposed approach is:

* Port the Runtime Expression object from OpenAPI 3.0.
* Add a Correlation ID object to the specification that describes both the type as a Schema object and the location as a Runtime Expression object.
* Add a Correlation ID property to the Message object that can reference/declare inline the Correlation ID object.

# Rationale

Reasons for approach are as follows:

* Generally speaking (although there are other use cases of course) correlation IDs are meaningful in the context of RPC style patterns that implement reply-to queue type mechanisms. By virtue of that fact Correlation IDs are probably best placed being specified on the Message object.
* However, having a reusable Correlation ID object would be a huge convenience for the designer so they can be included in multiple message specifications.
* Creating a Correlation ID object normalises it across providers i.e. some use headers, others message properties. By declaring it as a message attribute we can always deal with it in the same way
* By using a Runtime Expression we can engineer with flexibility. For example where there’s no Correlation ID out of the box for the messaging provider designers can implement a reference to something that might be in the message body.
* If the correlation ID comes from a nested field in the payload they can provide a clear and explicit reference in the Runtime Expression that is supported by the mechanics of the specification. For example, if the Correlation ID is in `$message.payload#/nestedFieldA/nestedFieldB/randomField` that can be unequivocally defined in the specification supported by an appropriate object.
* Using this approach lends itself well to RPC-style features in the backlog such as [reply-to-queue](https://github.com/asyncapi/asyncapi/issues/94)**.

# Example

The Correlation ID object implemented as a Runtime Expression & Schema Object:

```
MyCorrelationId:
  ‘{$message.header.correlationId}’:
    schema:
      type: string
      pattern: ‘^[0-9a-zA-Z]$’
```

Then a Message object would look like this:

```
MyNiceMessage:
  correlationId:
    $ref: ‘#/components/correlationIds/MyCorrelationId`
  payload:
    schema:
	 type: object
      properties:
        Fruit:
         type: string
         enum:
           - Banana
```

**Comment by mattheworiordan** [comment]
This is a very good idea 👍 

Other than that, no much feedback I am afraid.

**Comment by fmvilas** [comment]
This proposal looks good to me so far but I'd like to know why do we need to have a schema object inside the correlation id. How is this useful? I can't think on a correlation id that's something different than a string or a number.

I understand it can be useful to have something like a pattern but a whole schema object seems overkilling. What do you think?

**Comment by SensibleWood** [comment]
@fmvilas ☝️ 

> This proposal looks good to me so far but I'd like to know why do we need to have a schema object inside the correlation id. How is this useful? I can't think on a correlation id that's something different than a string or a number.

It adds flexibility without increasing complexity IMO. When I designer wants to enforce the fact that a correlation ID has to be an integer - for example - the capability is there to be used in a well-understood way.

> I understand it can be useful to have something like a pattern but a whole schema object seems overkilling. What do you think?

Essentially it doesn't "cost" the specification anything to define it as a Schema object and allows the designer to easily define as a number or a string using a well-understood lexicon. An option could be to cut down the Schema object so only primitives are supported - but then we introduce another construct to the specification that needs maintenance and increases bloat. For me just reusing the Schema object is the lesser of two evils in that scenario.

**Comment by SensibleWood** [comment]
☝️ 

Roughly this is what a "Simple Type" object might look like if we go down that road:

```
{
    "id": "http://json-schema.org/draft-04/schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Core schema meta-schema",
    "definitions": {
        "schemaArray": {
            "type": "array",
            "minItems": 1,
            "items": { "$ref": "#" }
        },
        "positiveInteger": {
            "type": "integer",
            "minimum": 0
        },
        "positiveIntegerDefault0": {
            "allOf": [ { "$ref": "#/definitions/positiveInteger" }, { "default": 0 } ]
        },
        "simpleTypes": {
            "enum": [ "integer", "number", "string" ]
        }
    },
    "type": "object",
    "properties": {
        "id": {
            "type": "string"
        },
        "$schema": {
            "type": "string"
        },
        "title": {
            "type": "string"
        },
        "description": {
            "type": "string"
        },
        "default": {},
        "multipleOf": {
            "type": "number",
            "minimum": 0,
            "exclusiveMinimum": true
        },
        "maximum": {
            "type": "number"
        },
        "exclusiveMaximum": {
            "type": "boolean",
            "default": false
        },
        "minimum": {
            "type": "number"
        },
        "exclusiveMinimum": {
            "type": "boolean",
            "default": false
        },
        "maxLength": { "$ref": "#/definitions/positiveInteger" },
        "minLength": { "$ref": "#/definitions/positiveIntegerDefault0" },
        "pattern": {
            "type": "string",
            "format": "regex"
        },
        "additionalItems": {
            "anyOf": [
                { "type": "boolean" },
                { "$ref": "#" }
            ],
            "default": {}
        },
        "uniqueItems": {
            "type": "boolean",
            "default": false
        },
        "required": { "$ref": "#/definitions/stringArray" },
        "additionalProperties": {
            "anyOf": [
                { "type": "boolean" },
                { "$ref": "#" }
            ],
            "default": {}
        },
        "definitions": {
            "type": "object",
            "additionalProperties": { "$ref": "#" },
            "default": {}
        },
        "properties": {
            "type": "object",
            "additionalProperties": { "$ref": "#" },
            "default": {}
        },
        "patternProperties": {
            "type": "object",
            "additionalProperties": { "$ref": "#" },
            "default": {}
        },
        "dependencies": {
            "type": "object",
            "additionalProperties": {
                "anyOf": [
                    { "$ref": "#" },
                    { "$ref": "#/definitions/stringArray" }
                ]
            }
        },
        "enum": {
            "type": "array",
            "minItems": 1,
            "uniqueItems": true
        },
        "type": { 
          "$ref": "#/definitions/simpleTypes" 
        },
        "format": { "type": "string" },
        "allOf": { "$ref": "#/definitions/schemaArray" },
        "anyOf": { "$ref": "#/definitions/schemaArray" },
        "oneOf": { "$ref": "#/definitions/schemaArray" },
        "not": { "$ref": "#" }
    },
    "dependencies": {
        "exclusiveMaximum": [ "maximum" ],
        "exclusiveMinimum": [ "minimum" ]
    },
    "default": {}
}
```

**Comment by SensibleWood** [comment]
OK I'm proceeding on the basis of a cutdown Schema object that only supports the following:

```
"simpleTypes": { "enum": [ "integer", "number", "string" ] }
```

I think I can create with minimal bloat through referencing the Schema object and using `not` to constrain the behaviours e.g. no objects, arrays, etc... BRB with an implementation...

**Comment by SensibleWood** [comment]
☝️ PR submitted for feature

**Comment by fmvilas** [comment]
🎉
