### ISSUE TITLE
HTTP and HTTPS schemes are missing

### ISSUE THREAD

**Issue by fmvilas** [asyncapi/asyncapi#81]
HTTP and HTTPS schemes are missing in human-readable documentation, i.e., in the README.

**Comment by mattheworiordan** [comment]
What is `HTTP` and `HTTPS` as a scheme in regards to AsyncAPI?  Specifically, HTTP is a request/response mechanism, so how would a client generically use HTTP and HTTPS as a transport and scheme for a message orientated connection?

**Comment by fmvilas** [comment]
We also support streaming APIs since version 1.2.0: https://github.com/asyncapi/asyncapi#streamObject.

Check out this example: https://github.com/asyncapi/asyncapi/blob/v2/test/docs/gitter-streaming.yaml

**Comment by vadeg** [comment]
@fmvilas Could you please clarify when version `1.3.0` will be released?

**Comment by fmvilas** [comment]
Closing as it's already fixed in #151.
