### ISSUE TITLE
specification-extensions

### ISSUE THREAD

**Issue by AtosNicoS** [asyncapi/asyncapi#83]
https://github.com/asyncapi/asyncapi#specification-extensions

The current pattern is defined as `^x-` But I think it should rather be `^x-.*`?

This is also wrongly defined in the json schema. I am wondering if you evenuse it for validation. If yes, there must be something wrong I guess.

**Comment by fmvilas** [comment]
Yes, it's being used for validation and it's totally correct as it is :)
