### ISSUE TITLE
serverVariableObject missing examples

### ISSUE THREAD

**Issue by AtosNicoS** [asyncapi/asyncapi#84]
https://github.com/asyncapi/asyncapi#serverVariableObject

### Usecase:
I want to specify additional variables for connecting to the MQTT broker: username and password. I want to provide a sample for the username, e.g. "MyUsername". Examples should be always inside an array.

Do you think that is useful? One could work around this by adding additional description text.

**Comment by fmvilas** [comment]
Yes, this is a good idea. Mind a PR?
