### ISSUE TITLE
Allow merging of $ref and schema

### ISSUE THREAD

**Issue by AtosNicoS** [asyncapi/asyncapi#85]
My goal is to define a default header (with QoS, retain etc) that I want to specify in detail with more properties:
```yaml
      headers:
        $ref: "#/components/schemas/subscribe_header"
        properties:
          userProperties:
            [...]
```

If I am not wrong this is a new feature of the json schema draft 08, which is not yet released (but I might have missunderstood, so please check!). It should be considered to be used.
https://github.com/json-schema-org/json-schema-spec/pull/628
https://github.com/json-schema-org/json-schema-spec/issues/523

**Comment by fmvilas** [comment]
You can use `allOf`. Check https://fmvilas.com/docgen-now-supports-asyncapi-1-1-0-and-more/
