### ISSUE TITLE
Add a section for definitions

### ISSUE THREAD

**Issue by AtosNicoS** [asyncapi/asyncapi#86]
I my topic tree I always have a variable called "serial":
```yaml
topics:
  event.teltonika.{serial}.mobile.bytes_received:
    parameters:
      - $ref: "#/x-definitions/serial_parameter"
    subscribe:
      [...]

x-definitions:
  serial_parameter:
          name: "serial"
          description: "Serial number of the router. Serial number can be taken from the device or via the command: `uci get hwinfo.hwinfo.serial`."
          schema:
            type: "string"
            title: "Serial number"
            description: "Serial number, usually 8 digests long."
            example: "01234567"
```

I want to use the parameters defintion of serial more often, so I needed to place it somewhere else. I found out, that I have no chance to put it under any subtype of the components section. So I used a self defined `x-definitions`.

Now my question is: Am I missing something, is there a better way to do this task? If not, what about adding a place for such definitions?

**Comment by MikeRalphson** [comment]
In AsyncAPI 1.2.0 you can use `components/parameters`

**Comment by AtosNicoS** [comment]
Yes, that is exactly what I need. But the online editor does not support the API 1.2.0 yet, right?

**Comment by fmvilas** [comment]
No, the editor is not yet updated. I need to find some time to update all the tooling yet. 

The editor is [here](https://github.com/asyncapi/editor), so if you need it soon you might want to hack it yourself. I'll take care of the deployment.
