### ISSUE TITLE
TypeError: Class constructor MqttAdapter cannot be invoked without 'new'

### ISSUE THREAD

**Issue by mikekekekeke** [asyncapi/asyncapi#88]
After all steps in your tutorial (www.asyncapi.com/v1/tutorial/), after running 'npm start' it throws an error like '
const adapter = hermesMQTT({
                ^

TypeError: Class constructor MqttAdapter cannot be invoked without 'new'
'. What is missed from my side?..

**Comment by fmvilas** [comment]
I'm not sure what can be failing there. Can you share your package.json file with me?

**Comment by mikekekekeke** [comment]
Sure
`{
  "name": "streetlights_api",
  "description": "The Smartylighting Streetlights API allows you to remotely manage the city lights. ",
  "version": "1.0.0",
  "scripts": {
    "start": "node src/api/index.js"
  },
  "dependencies": {
    "hermesjs": "1.x",
    "hermesjs-router": "1.x",
    "hermesjs-mqtt": "latest",
    "node-yaml-config": "0.0.4"
  }
}
`

**Comment by mikekekekeke** [comment]
Sure

```
{
  "name": "streetlights_api",
  "description": "The Smartylighting Streetlights API allows you to remotely manage the city lights. ",
  "version": "1.0.0",
  "scripts": {
    "start": "node src/api/index.js"
  },
  "dependencies": {
    "hermesjs": "1.x",
    "hermesjs-router": "1.x",
    "hermesjs-mqtt": "latest",
    "node-yaml-config": "0.0.4"
  }
}

```

**Comment by fmvilas** [comment]
Ok I know what's happening. The package `hermesjs-mqtt` should be using version `1.1.1`. Version 2 (latest) is only compatible with Hermes 2.

**Comment by mikekekekeke** [comment]
So, seems it helped. Thanks!
