### ISSUE TITLE
Your schema contains $ref. You must provide specification in the third parameter.

### ISSUE THREAD

**Issue by JanEggers** [asyncapi/asyncapi#90]
im trying to update my api with http://editor.asyncapi.org/

I get the errormessage:

Your schema contains $ref. You must provide specification in the third parameter.

Can you please clarify the meaning of that message?

I created the spec back at the 16.03.2018 at that time the document was considered valid.

**Comment by MikeRalphson** [comment]
Sounds suspiciously like a message from https://github.com/APIs-guru/openapi-sampler

**Comment by fmvilas** [comment]
Mmmm, interesting. Will investigate in the upcoming days. Thanks for reporting @JanEggers and thanks for the clue @MikeRalphson!

**Comment by fmvilas** [comment]
I updated the editor so it doesn't fail, but documentation will not get rendered correctly anyway.

**Comment by JanEggers** [comment]
thx
