### ISSUE TITLE
No OAuth support in specification

### ISSUE THREAD

**Issue by SensibleWood** [asyncapi/asyncapi#93]
Hey, just wondering on the rationale for not including OAuth support in the Security Schemes?

Whilst this may not make sense in many protocols in the WebSocket case presenting an access token which is granted an appropriate scope when connecting over HTTPS (and expected an upgrade to WSS) seems to make sense to me.

Describing this schematically would be really useful (especially for the work I'm doing ATM, which is exactly this scenario).

**Comment by fmvilas** [comment]
You're right. WebSockets support is relatively new, and I wanted to keep it simple for the first release, but that's definitely something that needs to be there in future releases.

**Comment by SensibleWood** [comment]
Happy to help with it! I'll work it up and let you know when its ready for review

**Comment by fmvilas** [comment]
Awesome Chris! Let me know if you need help along the way. I'll be happy to help!
