### ISSUE TITLE
Question: broker support for api generation

### ISSUE THREAD

**Issue by JanEggers** [asyncapi/asyncapi#96]
Hi there,

I didnt find any brokers that support generating the api spec! (the ecosystem tab in your site is quite empty)

I really like the idea of https://github.com/domaindrivendev/Swashbuckle e.g. a plugin for server tech that makes the implementation discoverable.

Im currently using mqttnet https://github.com/chkr1011/MQTTnet which is a fine broker, but currently im stitching together the api spec manually with your online editor. so it is only partially up to date.... 

I would prefere to run the mqttserver and let a client push each subject once so I can than have an api spec generated for me.

Also if such a feature is not a thing yet, is there any .net library you can suggest I could use to build such a meta endpoint?

**Comment by fmvilas** [comment]
I think this is more a feature of a particular tool than the spec itself unless I didn't understand correctly :)

Honestly, I never used .NET technologies, so can't help so much there. I can help you if you decide to create such tooling. Let me know.
