### ISSUE TITLE
AsyncAPIfy existing REST services

### ISSUE THREAD

**Issue by copitz** [asyncapi/asyncapi#97]
Hi there,

I really appreciate your efforts on standardizing message driven APIs!

As probably some others out there, we have REST APIs which are also documented using swagger or OAS 3.0 which is fine but we struggle to provide real time functionality with them. Of course we could just add some WebSocket functionality maybe even documented with AsynAPI. However this would feel a bit odd as it would mean to more or less reimplement all the functionality of the REST APIs.

Our idea to easily add this realtime functionality to existing REST APIs now is, to put a kind of proxy server between the clients and the APIs which would:

1. Translate their Swagger/OAS specs to AsyncAPI (so that paths and operations/verbs would be translated to topics)
2. Provide a STOMP endpoint for clients which would expose suitable functions for the Swagger operations and a PubSub system to inform clients when changes have happened to resources they subscribed to.
3. Proxy regular REST requests to the original API to detect changes for the PubSub system automatically and let the STOMP clients know.
4. Provide a HTTP endpoint for the applications providing the REST APIs (or any other, internal apps) to publish topics "manually".

Finally my two questions are:

1. Do you know any frameworks, services or libraries doing all or parts of this?
2. Would you be interested in joining or even conducting a project like this?

Thanks,
Christian

**Comment by fmvilas** [comment]
Hi Christian. Sounds like a fun project. I've never heard of anyone or any framework that could help in doing that. I'd be happy to help your company move forward on that matter. Just drop me a line at fmvilas@gmail.com, or [join the Slack channel](https://async-apis-slack.herokuapp.com/) and send me a DM.
